### ISSUE TITLE
请教一个问题，关于自定义数据集与模型训练

### ISSUE THREAD

**Issue by DXVVV** [PaddlePaddle/PaddleSeg#1076]
是这样的，我自定义了个一个数据集，格式和推荐的一样，即/images，/labels，然后在bisenet上也跑过了，但是我打算尝试decoupled_segnet的时候修改config然后训练报错了，想问下怎么做标价好，贴上config和报错信息。
config
```
batch_size: 4
iters: 80000

model:
  type: DecoupledSegNet
  backbone:
    type: ResNet50_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  num_classes: 6
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: OhemCrossEntropyLoss
    - type: RelaxBoundaryLoss
    - type: BCELoss
      weight: 'dynamic'
      edge_label: True
    - type: OhemEdgeAttentionLoss
  coef: [1,1,25,1]

train_dataset:
  edge: True

train_dataset: #训练数据设置
  type: Dataset #选择数据集格式
  dataset_root: data/custom_dataset #选择数据集路径
  train_path: data/custom_dataset/train.txt
  num_classes: 6 #指定目标的类别个数（背景也算为一类）
  transforms: #数据预处理/增强的方式
    - type: Resize #送入网络之前需要进行resize
      target_size: [512, 512] #将原图resize成512*512在送入网络
    - type: RandomHorizontalFlip #采用水平反转的方式进行数据增强
    - type: Normalize #图像进行归一化
  mode: train

val_dataset: #验证数据设置
  type: Dataset #选择数据集格式
  dataset_root: data/custom_dataset #选择数据集路径
  val_path: data/custom_dataset/val.txt
  num_classes: 6 #指定目标的类别个数（背景也算为一类）
  transforms: #数据预处理/增强的方式
    - type: Resize  #将原图resize成512*512在送入网络
      target_size: [512, 512]  #将原图resize成512*512在送入网络
    - type: Normalize #图像进行归一化
  mode: val
```
报错信息，多加了一行打印变量，似乎后者为null，但是我实在不知道怎么办了= =
```
python train.py        --config configs/decoupled_segnet/myconfig.yml        --do_eval        --use_vdl        --save_dir output1
/home/muli/anaconda3/lib/python3.7/site-packages/socks.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Callable
2021-06-08 16:55:46 [INFO]	
------------Environment Information-------------
platform: Linux-4.15.0-115-generic-x86_64-with-debian-stretch-sid
Python: 3.7.0 (default, Jun 28 2018, 13:15:42) [GCC 7.2.0]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.2, V10.2.89
cudnn: 7.0
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: Tesla K80', 'GPU 1: Tesla K80']
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PaddlePaddle: 2.1.0
OpenCV: 4.4.0
------------------------------------------------
2021-06-08 16:55:46 [INFO]	
---------------Config Information---------------
batch_size: 4
iters: 80000
loss:
  coef:
  - 1
  - 1
  - 25
  - 1
  types:
  - ignore_index: 255
    type: OhemCrossEntropyLoss
  - ignore_index: 255
    type: RelaxBoundaryLoss
  - edge_label: true
    ignore_index: 255
    type: BCELoss
    weight: dynamic
  - ignore_index: 255
    type: OhemEdgeAttentionLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  align_corners: false
  aspp_out_channels: 256
  aspp_ratios:
  - 1
  - 12
  - 24
  - 36
  backbone:
    multi_grid:
    - 1
    - 2
    - 4
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
    type: ResNet50_vd
  backbone_indices:
  - 0
  - 3
  num_classes: 6
  pretrained: null
  type: DecoupledSegNet
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: data/custom_dataset
  mode: train
  num_classes: 6
  train_path: data/custom_dataset/train.txt
  transforms:
  - target_size:
    - 512
    - 512
    type: Resize
  - type: RandomHorizontalFlip
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: data/custom_dataset
  mode: val
  num_classes: 6
  transforms:
  - target_size:
    - 512
    - 512
    type: Resize
  - type: Normalize
  type: Dataset
  val_path: data/custom_dataset/val.txt
------------------------------------------------
W0608 16:55:46.646091 11692 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 3.7, Driver API Version: 10.2, Runtime API Version: 10.2
W0608 16:55:46.646126 11692 device_context.cc:422] device: 0, cuDNN Version: 7.0.
W0608 16:55:48.051836 11692 device_context.h:360] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
2021-06-08 16:55:48 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
2021-06-08 16:55:49 [INFO]	There are 275/275 variables loaded into ResNet_vd.
/home/muli/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:239: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int32, the right dtype will convert to paddle.float32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
/home/muli/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:239: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, the right dtype will convert to paddle.float32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
/home/muli/xiang/paddle/PaddleSeg/paddleseg/models/losses/ohem_cross_entropy_loss.py:93: DeprecationWarning: 
Warning:
API "paddle.nn.functional.loss.softmax_with_cross_entropy" is deprecated since 2.0.0, and will be removed in future versions. Please use "paddle.nn.functional.cross_entropy" instead.
reason: Please notice that behavior of "paddle.nn.functional.softmax_with_cross_entropy" and "paddle.nn.functional.cross_entropy" is different. 
  logit, label, ignore_index=self.ignore_index, axis=1)
/home/muli/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:239: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.int64, but right dtype is paddle.float32, the right dtype will convert to paddle.int64
  format(lhs_dtype, rhs_dtype, lhs_dtype))
logit  Tensor(shape=[4, 1, 512, 512], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[[[0.60411680, 0.60411680, 0.62150568, ..., 0.48534459, 0.48020831, 0.48020831],
          [0.60411680, 0.60411680, 0.62150568, ..., 0.48534459, 0.48020831, 0.48020831],
          [0.61717361, 0.61717361, 0.63606143, ..., 0.50431585, 0.50495517, 0.50495517],
          ...,
          [0.54608011, 0.54608011, 0.52774680, ..., 0.47467729, 0.45920396, 0.45920396],
          [0.55205119, 0.55205119, 0.52762854, ..., 0.44078678, 0.42475531, 0.42475531],
          [0.55205119, 0.55205119, 0.52762854, ..., 0.44078678, 0.42475531, 0.42475531]]],


        [[[0.15018667, 0.15018667, 0.18593560, ..., 0.35553807, 0.34993255, 0.34993255],
          [0.15018667, 0.15018667, 0.18593560, ..., 0.35553807, 0.34993255, 0.34993255],
          [0.23165587, 0.23165587, 0.26055160, ..., 0.38540149, 0.38505453, 0.38505453],
          ...,
          [0.51588780, 0.51588780, 0.54416621, ..., 0.68268967, 0.67901492, 0.67901492],
          [0.48848975, 0.48848975, 0.51883888, ..., 0.64975280, 0.64177394, 0.64177394],
          [0.48848975, 0.48848975, 0.51883888, ..., 0.64975280, 0.64177394, 0.64177394]]],


        [[[0.66901869, 0.66901869, 0.68446070, ..., 0.62128222, 0.63231987, 0.63231987],
          [0.66901869, 0.66901869, 0.68446070, ..., 0.62128222, 0.63231987, 0.63231987],
          [0.66955107, 0.66955107, 0.67974430, ..., 0.62197709, 0.63860488, 0.63860488],
          ...,
          [0.75839925, 0.75839925, 0.73420733, ..., 0.60707116, 0.59692568, 0.59692568],
          [0.75956023, 0.75956023, 0.73458141, ..., 0.58367729, 0.57073998, 0.57073998],
          [0.75956023, 0.75956023, 0.73458141, ..., 0.58367729, 0.57073998, 0.57073998]]],


        [[[0.44814259, 0.44814259, 0.43638745, ..., 0.52429324, 0.51752567, 0.51752567],
          [0.44814259, 0.44814259, 0.43638745, ..., 0.52429324, 0.51752567, 0.51752567],
          [0.44611016, 0.44611016, 0.43685114, ..., 0.53810662, 0.53495288, 0.53495288],
          ...,
          [0.80893320, 0.80893320, 0.81274283, ..., 0.52628654, 0.50992489, 0.50992489],
          [0.81153184, 0.81153184, 0.81404358, ..., 0.49473548, 0.47846800, 0.47846800],
          [0.81153184, 0.81153184, 0.81404358, ..., 0.49473548, 0.47846800, 0.47846800]]]])  label  None
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    main(args)
  File "train.py", line 163, in main
    keep_checkpoint_max=args.keep_checkpoint_max)
  File "/home/muli/xiang/paddle/PaddleSeg/paddleseg/core/train.py", line 151, in train
    edges=edges)
  File "/home/muli/xiang/paddle/PaddleSeg/paddleseg/core/train.py", line 44, in loss_computation
    loss_list.append(losses['coef'][i] * loss_i(logits, edges))
  File "/home/muli/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/muli/xiang/paddle/PaddleSeg/paddleseg/models/losses/binary_cross_entropy_loss.py", line 134, in forward
    if len(label.shape) != len(logit.shape):
AttributeError: 'NoneType' object has no attribute 'shape'

```
