### ISSUE TITLE
训练时精度无变化

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleSeg#1093]
您好，我在训练两类的分割模型，未标注的是255，两类是0和1。训练几次后的IOU和ACC kappa一直不变。
2021-06-19 13:04:47 [INFO]	[EVAL] #Images: 211 mIoU: 0.3900 Acc: 0.7800 Kappa: 0.0000 
2021-06-19 13:04:47 [INFO]	[EVAL] Class IoU: 
[0.78 0.  ]
2021-06-19 13:04:47 [INFO]	[EVAL] Class Acc: 
[0.78 0.  ]

配置参数：如下
```
_base_: './configs/_base_/pascal_voc12aug.yml'
batch_size: 2  #设定batch_size的值即为迭代一次送入网络的图片数量，一般显卡显存越大，batch_size的值可以越大
iters: 2000    #模型迭代的次数

train_dataset: #训练数据设置
  type: Dataset #选择数据集格式，遥感数据集，在paddleseg/datasets中新定义一个类DatasetRS
  dataset_root: /home/wang/PaddleSeg/data/df_dataset_20210531 #选择数据集路径
  train_path: /home/wang/PaddleSeg/data/df_dataset_20210531/train_list.txt
  num_classes: 2 #指定目标的类别个数（背景也算为一类）
  transforms: #数据预处理/增强的方式
    - type: RandomHorizontalFlip #采用水平反转的方式进行数据增强
  mode: train

val_dataset: #验证数据设置
  type: Dataset #选择数据集格式
  dataset_root: /home/wang/PaddleSeg/data/df_dataset_20210531 #选择数据集路径
  val_path: /home/wang/PaddleSeg/data/df_dataset_20210531/val_list.txt
  num_classes: 2 #指定目标的类别个数（背景也算为一类）
  mode: val

optimizer: #设定优化器的类型
  type: sgd #采用SGD（Stochastic Gradient Descent）随机梯度下降方法为优化器
  momentum: 0.9 #动量
  weight_decay: 4.0e-5 #权值衰减，使用的目的是防止过拟合


learning_rate: #设定学习率
  value: 0.05  #初始学习率
  decay:
    type: poly  #采用poly作为学习率衰减方式。
    power: 0.95  #衰减率
    end_lr: 0   #最终学习率

loss: #设定损失函数的类型
  types:
    - type: CrossEntropyLoss #损失函数类型

model:
  type: DeepLabV3P
  backbone:
    type: ResNet50_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null
```
