### ISSUE TITLE
优化器为adam的时候报错

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleSeg#1095]
Hello，配置文件里优化器改为adam的时候报错，我在配置文件里把momentum注释掉和不注释都报错。
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    main(args)
  File "train.py", line 153, in main
    optimizer=cfg.optimizer,
  File "/home/aistudio/work/PaddleSeg/paddleseg/cvlibs/config.py", line 196, in optimizer
    lr, parameters=self.model.parameters(), **args)
TypeError: __init__() got an unexpected keyword argument 'momentum'

**Comment by nepeplwu** [comment]
@kingbirdWc 麻烦贴下你的配置文件

**Comment by kingbirdWc** [comment]
```
_base_: './configs/_base_/pascal_voc12aug.yml'
batch_size: 8 #设定batch_size的值即为迭代一次送入网络的图片数量，一般显卡显存越大，batch_size的值可以越大
iters: 1000    #模型迭代的次数

train_dataset: #训练数据设置
  type: Dataset #选择数据集格式，遥感数据集，在paddleseg/datasets中新定义一个类DatasetRS
  dataset_root: /home/aistudio/work/df_dataset_20210531 #选择数据集路径
  train_path: /home/aistudio/work/df_dataset_20210531/train_list.txt
  num_classes: 2 #指定目标的类别个数（背景也算为一类）
  #transforms: #数据预处理/增强的方式
  #  - type: RandomHorizontalFlip #采用水平反转的方式进行数据增强
  #  - type: Normalize #图像进行归一化
  mode: train

val_dataset: #验证数据设置
  type: Dataset #选择数据集格式
  dataset_root: /home/aistudio/work/df_dataset_20210531 #选择数据集路径
  val_path: /home/aistudio/work/df_dataset_20210531/val_list.txt
  num_classes: 2 #指定目标的类别个数（背景也算为一类）
  #transforms: #数据预处理/增强的方式
  #  - type: Normalize #图像进行归一化
  mode: val

optimizer: #设定优化器的类型
  type: adam #采用SGD（Stochastic Gradient Descent）随机梯度下降方法为优化器
#  momentum: 0.9 #动量
#  weight_decay: 4.0e-5 #权值衰减，使用的目的是防止过拟合


learning_rate: #设定学习率
  value: 0.1  #初始学习率
  decay:
    type: poly  #采用poly作为学习率衰减方式。
    power: 0.95  #衰减率
    end_lr: 0   #最终学习率

loss: #设定损失函数的类型
  types:
    - type: CrossEntropyLoss #损失函数类型
  coef: [1]
  #BiseNetV2有4个辅助loss，加上主loss共五个，1表示权重 all_loss = coef_1 * loss_1 + .... + coef_n * loss_n

model:
  type: DeepLabV3P
  backbone:
    type: ResNet50_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    #pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null
```
