### ISSUE TITLE
Config problems about MixedLoss

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#1106]
I have tried all the methods in the project.
In the readme doc,the example lile `loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]`

while , in the config file yml , it likes this : `loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
  coef: [1, 0.4]`

Finally, it cannot run the training project

**Comment by LutaoChu** [comment]
The example represents a single mixed loss. There are two mixed losses in yml, because ocrnet outputs two logits, and each mixed loss corresponds to each logits.

**Comment by BeyondYourself** [comment]
The question is that my program dosen't work properly.
The error infomationas follows：
`Traceback (most recent call last):
  File "train.py", line 162, in <module>
    main(args)
  File "train.py", line 134, in main
    losses = cfg.loss
  File "/home/aistudio/work/PaddleSeg/paddleseg/cvlibs/config.py", line 236, in loss
    'Loss config should contain keys of "types" and "coef"')
ValueError: Loss config should contain keys of "types" and "coef"`

**Comment by BeyondYourself** [comment]
The loss of config as follows:
`loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]`

and I trained with  Unet3Plus model

**Comment by LutaoChu** [comment]
Well, each `loss` class corresponds to a `coef`. You also need to add a `coef` at the end, as follows
```
loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
  coef: [1]
```

**Comment by BeyondYourself** [comment]
> Well, each `loss` class corresponds to a `coef`. You also need to add a `coef` at the end, as follows
> 
> ```
> loss:
>   types:
>     - type: MixedLoss
>       losses:
>         - type: CrossEntropyLoss
>         - type: LovaszSoftmaxLoss
>       coef: [0.8, 0.2]
>   coef: [1]
> ```

Based on above format,  the new errorr arise：
`raceback (most recent call last):
  File "train.py", line 162, in <module>
    main(args)
  File "train.py", line 157, in main
    keep_checkpoint_max=args.keep_checkpoint_max)
  File "/home/aistudio/work/PaddleSeg/paddleseg/core/train.py", line 151, in train
    edges=edges)
  File "/home/aistudio/work/PaddleSeg/paddleseg/core/train.py", line 37, in loss_computation
    check_logits_losses(logits_list, losses)
  File "/home/aistudio/work/PaddleSeg/paddleseg/core/train.py", line 33, in check_logits_losses
    .format(len_logits, len_losses))
RuntimeError: The length of logits_list should equal to the types of loss config: 5 != 1.`

the logit_list is a tensor list  , the losses['types'] = MixedLoss( )    
In my training programe, the classes =5

**Comment by LutaoChu** [comment]
If your logit_ list has five logits. You should configure a mixedloss for each logit.
Like this
```
loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
  coef: [1, 1, 1, 1, 1]
```
Those `coef` are set according to your task.

**Comment by BeyondYourself** [comment]
OK ,I get it.  Whether we can  optimize it here, because there are exist a lot of  duplicate codes。
I had ever tested the non-mixed_losses  , that I only need to config like this: 
`loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]`

**Comment by LutaoChu** [comment]
If all your losses are the same, you can configure them like this, and paddleseg will automatically copy 5 losses. This is much simpler.
```
loss:
  types: 
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
  coef: [1, 1, 1, 1, 1]
```

**Comment by BeyondYourself** [comment]
In fact , it doesn't work.
`Traceback (most recent call last):
  File "train.py", line 162, in <module>
    main(args)
  File "train.py", line 157, in main
    keep_checkpoint_max=args.keep_checkpoint_max)
  File "/home/aistudio/work/PaddleSeg/paddleseg/core/train.py", line 132, in train
    for data in loader:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 351, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)
`

**Comment by LutaoChu** [comment]
The error message shows that this is a problem with dataloader, not loss. I tried bisenetv2. It's OK. Here's my yml for reference

```
_base_: '../_base_/cityscapes_769x769.yml'

model:
  type: BiSeNetV2
  num_classes: 19

optimizer:
  type: sgd
  weight_decay: 0.0005

loss:
  types: 
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
  coef: [1, 1, 1, 1, 1]

batch_size: 4
iters: 160000

learning_rate:
  value: 0.05
  decay:
    type: poly
    power: 0.9
    end_lr: 0.0
```
