### ISSUE TITLE
GSCNN实现正确吗？

### ISSUE THREAD

**Issue by parap1uie-s** [PaddlePaddle/PaddleSeg#1181]
GSCNN模型中，边缘输出为sigmoid激活后的结果

https://github.com/PaddlePaddle/PaddleSeg/blob/05a94f937425c898f09c2e4e08aafe831ff46c04/paddleseg/models/gscnn.py#L213
```
        edge_out = F.sigmoid(cs)  # Ouput of shape stream
```

并且配置文件中使用BCELoss训练edge_out
https://github.com/PaddlePaddle/PaddleSeg/blob/05a94f937425c898f09c2e4e08aafe831ff46c04/configs/gscnn/gscnn_resnet50_os8_cityscapes_1024x512_80k.yml#L24

```
loss:
  types:
    - type: CrossEntropyLoss
    - type: EdgeAttentionLoss
    - type: BCELoss
      edge_label: True
    - type: DualTaskLoss
  coef: [1, 1, 20, 1]
```

而BCELoss默认接受一个logit，而非sigmoid激活值
https://github.com/PaddlePaddle/PaddleSeg/blob/05a94f937425c898f09c2e4e08aafe831ff46c04/paddleseg/models/gscnn.py#L213
```
        loss = paddle.nn.functional.binary_cross_entropy_with_logits(
            logit,
            label,
            weight=weight,
            reduction='none',
            pos_weight=pos_weight)
```
