### ISSUE TITLE
deeplabv3p loss问题

### ISSUE THREAD

**Issue by yuemengrui** [PaddlePaddle/PaddleSeg#1238]
loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [0.4, 1]

为什么这样的loss配置会报错？报错如下：
Traceback (most recent call last):
  File "train.py", line 191, in <module>
    main(args)
  File "train.py", line 186, in main
    fp16=args.fp16)
  File "/home/aistudio/My_PaddleSeg/paddleseg/core/train.py", line 185, in train
    edges=edges)
  File "/home/aistudio/My_PaddleSeg/paddleseg/core/train.py", line 37, in loss_computation
    check_logits_losses(logits_list, losses)
  File "/home/aistudio/My_PaddleSeg/paddleseg/core/train.py", line 33, in check_logits_losses
    .format(len_logits, len_losses))
RuntimeError: The length of logits_list should equal to the types of loss config: 1 != 2.

loss:
 types:
   - type: CrossEntropyLoss
 coef: [1]
这样的loss配置可以正常训练
为什么不能配置不同权重的两个loss？

**Comment by nepeplwu** [comment]
@yuemengrui ，你所贴出来的这种写法只有当模型有两个输出时才适用，可以使用下面的方式来设置混合Loss
```yaml
loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: CrossEntropyLoss
      coef: [1, 0.4]
  coef: [1]
```

可以自行根据任务选择合适的Loss进行组合，如果是想使用两个CrossEntropy的话，这样是设置并没有意义，因为两个CrossEntropy监督的都是同个输出，最终的结果等同于

```yaml
loss:
  types:
    - type: CrossEntropyLoss
  coef: [1.4]
```
