### ISSUE TITLE
deeplab3p backbone使用MobileNetV3_large_x1_0 训练 ， export模型失败

### ISSUE THREAD

**Issue by pureloveljc** [PaddlePaddle/PaddleSeg#1251]
_base_: '../_base_/cityscapes.yml'

batch_size: 2
iters: 8000
model:
  type: DeepLabV3P
  backbone:
    type: MobileNetV3_large_x1_0
    output_stride: 32
h/MobileNetV3_large_x1_0.tar.gz
  num_classes: 2
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.02
  end_lr: 0
  power: 0.9

---
我的yml是这个 报错  是这个AssertionError: In transformed code:

    File "export.py", line 67, in forward (* user code *)
        outs = self.net(x)
    File "/home/ljc/miniconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
        outputs = self.forward(*inputs, **kwargs)
    File "/home/ljc/PaddleSeg/paddleseg/models/deeplab.py", line 83, in forward (* user code *)
        logit_list = self.head(feat_list)
    File "/home/ljc/miniconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
        outputs = self.forward(*inputs, **kwargs)
    File "/home/ljc/PaddleSeg/paddleseg/models/deeplab.py", line 153, in forward (* user code *)
        logit = self.decoder(x, low_level_feat)
    File "/home/ljc/miniconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
        outputs = self.forward(*inputs, **kwargs)
    File "/home/ljc/PaddleSeg/paddleseg/models/deeplab.py", line 298, in forward (* user code *)
        x = F.interpolate(
    File "/home/ljc/miniconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 366, in interpolate
        assert dim_size > 0, (
    AssertionError: Each dimension size given in out_shape must be greater than 0.

**Comment by nepeplwu** [comment]
@pureloveljc 感谢反馈，我们跟进下这个问题

**Comment by juncaipeng** [comment]
@pureloveljc  请问你使用paddle哪个版本，使用paddleseg哪个branch？

目前我使用develop版本的paddle，2.2分支的paddleseg，修改两个api错误（参考[pr](https://github.com/PaddlePaddle/PaddleSeg/pull/1256)）后，可以使用deeplabv3p_mobilenetv3_large_x1_0进行两分类的训练和导出。config如下：
```
train_dataset:
  type: OpticDiscSeg
  dataset_root: data/optic_disc_seg
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: OpticDiscSeg
  dataset_root: data/optic_disc_seg
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: Normalize
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

batch_size: 4
iters: 1000

model:
  type: DeepLabV3P
  backbone:
    type: MobileNetV3_large_x1_0
    output_stride: 32
    pretrained: null
  num_classes: 2
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null
```

从你的log中可以看出是输入interpolate的输入size错误，具体代码是[链接](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/paddleseg/models/deeplab.py#L300)，你可以在这个文件中输出多个tensor的shape看看，比如[feat_list](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/paddleseg/models/deeplab.py#L82), [x](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/paddleseg/models/deeplab.py#L152), [low_level_feat](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/paddleseg/models/deeplab.py#L291)
