### ISSUE TITLE
deeplabv3p resnet50的config在哪里？

### ISSUE THREAD

**Issue by heyyuhao** [PaddlePaddle/PaddleSeg#1333]
你好 请问 在PP-HumanSeg下面，configs里只有FCN的，有无deeplabv3p_resnet50的？

FCN config片段：
model:
  type: FCN
  backbone:
    type: HRNet_W18_Small_V1
    align_corners: False
  num_classes: 2
  pretrained: pretrained_model/fcn_hrnetw18_small_v1_humanseg_192x192/model.pdparams
  backbone_indices: [-1]

关于deeplabv3p_resnet50的model部分参数应该是什么？

谢谢

**Comment by LutaoChu** [comment]
是这样的
```
model:
  type: DeepLabV3
  backbone:
    type: ResNet50_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  backbone_indices: [3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null
```
