### ISSUE TITLE
Start evaluating数据时显存暴涨问题咨询？

### ISSUE THREAD

**Issue by HongShiKuan** [PaddlePaddle/PaddleSeg#1568]
目前我用2080TI（显存12G）训练deeplabv3p网络。paddlepaddle-gpu 2.2.0版本，paddleseg 2.3版本。图像分辨率4k。
**训练过程中显存占用6G附近，一到评估时，显存直接暴涨到11G多，然后再训练几个epoch直接暴显存**。
非常期待您的回复。
**报错如下**：
```
Out of memory error on GPU 0. Cannot allocate 1012.500244MB memory on GPU 0, 10.282471GB memory has been allocated and available memory is only 487.062500MB.
```
**运行指令如下**：
```
export CUDA_VISIBLE_DEVICES=1
python train.py \
       --config configs/my_config_deeplabv3p.yml \
       --do_eval \
       --use_vdl \
       --save_interval 500 \
       --save_dir output
```
**config配置如下**：
```
batch_size: 2
iters: 60000

model:
  type: DeepLabV3P
  backbone:
    type: ResNet50_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  num_classes: 2
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null


train_dataset:
  type: Dataset
  dataset_root: /home/fhy/workspace/bo/database
  train_path: /home/fhy/workspace/bo/database/train.txt
  num_classes: 2
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: /home/fhy/workspace/bo/database
  val_path: /home/fhy/workspace/bo/database/val.txt
  num_classes: 2
  transforms:
    - type: Normalize
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
```

**Comment by HongShiKuan** [comment]
猜测是预测时候不能直接将原图进行评估。将cofig中修改如下发现显存增长没那个迅猛了。
```
val_dataset:
  type: Dataset
  dataset_root: /home/fhy/workspace/bo/database
  val_path: /home/fhy/workspace/bo/database/val.txt
  num_classes: 2
  transforms:
    - type: Resize
      target_size: [1920, 1080]
    - type: Normalize
  mode: val
```
不知道是不是这个原因。
