### ISSUE TITLE
交叉熵损失指定weight时，触发ValueError(input's class_dimension(2) must equal to weight's class_dimension(256) when weight is provided)

### ISSUE THREAD

**Issue by step404** [PaddlePaddle/PaddleSeg#1582]
## 配置信息
- 操作系统： Ubuntu 20.04.1
- 库版本：
    - paddlepaddle-gpu : 2.2.0.post112
    - paddleseg: 2.3.0
--------------
将[此行](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/paddleseg/models/losses/cross_entropy_loss.py#L51)更改为：
```python
# long_weight = weight + [0] * (256 - len(weight))
self.long_weight = paddle.to_tensor(weight, dtype='float32')
```
可运行。

**Comment by haoyuying** [comment]
请问您使用的是什么模型，weight的shape是什么样子呢？

**Comment by step404** [comment]
@haoyuying 你好，我使用的模型是`sfnet_resnet18`，数据集是自定义的，类别数量为2，损失函数配置如下：
```yaml
loss:
  types:
    - type: MixedLoss
      losses:
        - type: MixedLoss
          losses:
            - type: FocalLoss
            - type: DiceLoss
          coef: [1, 1]
        - type: CrossEntropyLoss
          weight: [0.1, 1.0]
      coef: [1, 1]
  coef: [1]
```

**Comment by LutaoChu** [comment]
你好，该问题已经提pr了   https://github.com/PaddlePaddle/PaddleSeg/pull/1586

**Comment by step404** [comment]
非常感谢

**Comment by zhijiejia** [comment]
请问 问题解决了吗，我使用2.3还是会有这个问题。
```
loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
          ignore_index: 255
          weight: [2, 1, 2, 5]
        - type: DiceLoss
          ignore_index: 255
          smooth: 1.0e-5
      coef: [1, 1]
  coef: [1, 0.4]

model:
  type: PSPNet
  backbone:
    type: ResNet50_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  enable_auxiliary_loss: True
  align_corners: False
```
