### ISSUE TITLE
How to inference a BiSeNetV2 model (onnx) that was trained with custom data?

### ISSUE THREAD

**Issue by khaep** [PaddlePaddle/PaddleSeg#1616]
Hello there,

for semantic segmentation purpose, 
I have trained the BiSeNetV2 model with a custom data set.
After finishing the training process, I got reasonable predictions (about 77% mIoU) on the test dataset.
Doing some predictions with [predict.py](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/predict.py) (refer [doc](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/predict/predict.md)) also works fine for the first impressions.

Then, I want to deploy the trained model on the target system. Therefore I read the  [export](https://github-com.translate.goog/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/model_export.md?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=de) instructions and exported the model, so I get the described resulting files.

*  deploy.yaml
*  model.pdiparams
*  model.pdiparams.info
*  model.pdmodel

Now the question is how can I implement the inference of the trained model?
I am looking for something like a python script, that reads an input image, does the inference and returns the predicted image.
I saw that you provide a [script](https://github-com.translate.goog/PaddlePaddle/PaddleSeg/blob/release/2.3/deploy/python/infer.py?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=de) for inference. 
But which lines are necessary for the inference?

Additionaly I thought about converting the model from PaddleSeg to ONNX with [paddle2onnx](https://github-com.translate.goog/PaddlePaddle/Paddle2ONNX/blob/develop/README.md?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=de).
Maybe a custom inference script can look something like this: 

```python
import numpy as np
import cv2
import onnx
import onnxruntime
from onnx import numpy_helper

#set paths
img_path = "/home/PaddleSeg/raw_image.png"
model = "model.onnx"

#read image
img = cv2.imread(img_path)

#normalize the image
img = img.astype(np.float32)/255.0
#img = img - np.array([np.mean(img[:,:,0]), np.mean(img[:,:,1]), np.mean(img[:,:,2])])
#img = img / np.array([np.std(img[:,:,0]), np.std(img[:,:,1]), np.std(img[:,:,2])])

#add fourth dimension to fit input shape of the exported model [-1, 3, -1, -1]
img = np.expand_dims(img, 0)
img = np.transpose(img, (0, 3, 1, 2))

session = onnxruntime.InferenceSession(model, None, providers=["CUDAExecutionProvider"])

input_name = session.get_inputs()[0].name
output_name = session.get_outputs()[0].name

# here the inference is done
result = session.run([output_name], {input_name:np.float32(img)})

# convert the result back to an 320 x 640 image
pred_img = np.uint8(result[0])
pred_img = np.reshape(pred_img, (320, 640))
cv2.imwrite("result.png", pred_img)

```
By using this script, I get some predictions but they differ from the predictions that are created by using the [infer.py](https://github-com.translate.goog/PaddlePaddle/PaddleSeg/blob/release/2.3/deploy/python/infer.py?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=de) script.
So the question is, whats the reason for that?

Is there something wrong with the normalization compared to the run with [infer.py](https://github-com.translate.goog/PaddlePaddle/PaddleSeg/blob/release/2.3/deploy/python/infer.py?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=de)?
Perhaps, the mean and the standard deviation need to be considered at the normalization step.

Here is the content of the config.yml file, that was used for training. Maybe it is useful to answer the questions.
```yml

train_dataset:
  type: Dataset
  dataset_root: dataset
  train_path: dataset/train.txt
  num_classes: 2
  transforms:
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: dataset/FramesForVal/
  val_path: dataset/FramesForVal/val.txt
  num_classes: 2
  transforms:
    - type: Normalize
  mode: val

test_dataset:
  type: Dataset
  dataset_root: dataset/
  test_path: dataset/test.txt
  num_classes: 2
  transforms:
    - type: Normalize
  mode: test

model:
  type: BiSeNetV2
  num_classes: 2

optimizer:
  type: sgd
  weight_decay: 0.0005

loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1, 1, 1, 1, 1]

batch_size: 8
iters: 100000

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.05
  end_lr: 0.0
  power: 0.9

```
It would be greate if you can give me some answers or hints about that.
I look forward to hearing from you.

Kind regards
