### ISSUE TITLE
[General Issue]PaddleSeg使用Unet训练自定义的数据集报错

### ISSUE THREAD

**Issue by WangRongsheng** [PaddlePaddle/PaddleSeg#1923]
- PaddleSeg版本：最新
- 训练命令
```python
!python train.py \
       --config configs/unet/unet_chasedb1_128x128_40k.yml \
       --do_eval \
       --save_dir output
```
- 训练报错：
```html
ValueError: (InvalidArgument) The input tensor's dimension should be equal to the axis's size. But received input tensor's dimension is 5, axis's size is 4
  [Hint: Expected x_rank == axis_size, but received x_rank:5 != axis_size:4.] (at /paddle/paddle/fluid/operators/transpose_op.cc:47)
  [operator < transpose2 > error]
```
- 配置文件：
```yml
batch_size: 16
iters: 1000

train_dataset:
  type: CHASEDB1
  dataset_root: ./dataset/
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [128, 128]
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: CHASEDB1
  dataset_root: ./dataset/
  transforms:
    - type: Normalize
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: DiceLoss
  coef: [1]

test_config:
  auc_roc: True
```
- 数据集：
```html
├── Annotations
│   ├── 100.png
│   ├── 101.png
│   ├── 102.png
├── JPEGImages
│   ├── 100.png
│   ├── 101.png
│   ├── 102.png
├── labels.txt
├── train_list.txt
└── val_list.txt
```
--- 

请问该怎么解决
