### ISSUE TITLE
[Feature Request] Mattings预测时如何让一张图片的边缘变得清晰?

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#2115]
您好，我在采用`Mattings`训练出了一个模型，但是遇到些问题，希望能够得到您们的答复。如下：
我在进行预测时发现抠出来的图片中的边缘并不是很清晰。请问有什么参数或方法可以调整抠出来的图片的边缘比较清晰呢？

原图：
![bdb1b6763bb346c0875c6be6c05b5f58](https://user-images.githubusercontent.com/34839719/168512136-4cc3beb1-9cd5-4615-a0f4-648befaf3fd5.jpg)

抠出来的图：
![bdb1b6763bb346c0875c6be6c05b5f58](https://user-images.githubusercontent.com/34839719/168512196-74bfbf8f-df4b-49cf-9c8e-da00d3e6cbb9.png)

mask图：
![bdb1b6763bb346c0875c6be6c05b5f58](https://user-images.githubusercontent.com/34839719/168512253-e31c48a5-2ca6-47ec-bc6c-b3a020cd9977.png)

**Comment by wuyefeilin** [comment]
可以使用pp-matting-1024模型试试。

**Comment by zhenzi0322** [comment]
> 可以使用pp-matting-1024模型试试。

该模型不是还没有开源出来嘛？我上次就问过您，您说该模型暂未开源。

**Comment by wuyefeilin** [comment]
开源了部署模型，可以直接用来预测，参考文档部署部分哈
https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.5/Matting#deploy

**Comment by zhenzi0322** [comment]
> 我可能开源了部署模型，可以直接用来预测，参考文档部署部分哈 https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.5/Matting#deploy

对的，部署模型是更新了，解决了我一个预测后的图片体积过大的问题，但是我目前采用的就是`release/2.5`里最新部署模型。效果就如上面所说的边缘不够清晰。这个站点 https://588ku.com/koutu/index.html#/tool 抠出来的图片边缘是很清晰的。也是用的上面同一张图片。就是我们的`Mattings`模型要如何才能达到抠出来的图片边缘清晰就跟原图差不多。

**Comment by wuyefeilin** [comment]
可以把下载下来文件里面的deploy.yaml里的LimitShort给去掉，进行原图分辨率预测

**Comment by zhenzi0322** [comment]
> 可以把下载下来文件里面的deploy.yaml里的LimitShort给去掉，进行原图分辨率预测

我的导出模型中没有`LimitShort`这个参数。我的`deploy.yaml`如下：
```yaml
Deploy:
  model: model.pdmodel
  params: model.pdiparams
  transforms:
  - type: LoadImages
  - short_size: 512
    type: ResizeByShort
  - mult_int: 32
    type: ResizeToIntMult
  - type: Normalize
```

**Comment by wuyefeilin** [comment]
![image](https://user-images.githubusercontent.com/30919197/168941864-6fe56013-dc95-4356-a38b-c47806da798f.png)
把这一行删除就行了

**Comment by zhenzi0322** [comment]
> ![image](https://user-images.githubusercontent.com/30919197/168941864-6fe56013-dc95-4356-a38b-c47806da798f.png) 把这一行删除就行了

删除之后，我的`deploy.yaml`变成了这样：
```yaml
Deploy:
  model: model.pdmodel
  params: model.pdiparams
  transforms:
  - type: LoadImages
  - mult_int: 32
    type: ResizeToIntMult
  - type: Normalize
```
最后预测的效果如下：
![image](https://user-images.githubusercontent.com/34839719/168942660-6aa40ae3-4c66-4125-b7d1-1c42d2883761.png)

效果比之前的还要差了。

**Comment by zhenzi0322** [comment]
> ![image](https://user-images.githubusercontent.com/30919197/168941864-6fe56013-dc95-4356-a38b-c47806da798f.png) 把这一行删除就行了

这是我训练时使用的配置。如下：
```yml
batch_size: 16
iters: 200000

train_dataset:
  type: MattingDataset
  dataset_root: data/32877
  train_file: train.txt
  transforms:
    - type: LoadImages
    - type: ResizeByShort
      short_size: 512
    - type: RandomCrop
      crop_size: [512, 512]
    - type: RandomDistort
    - type: RandomBlur
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: MattingDataset
  dataset_root: data/32877
  val_file: val.txt
  transforms:
    - type: LoadImages
    - type: ResizeByShort
      short_size: 512
    - type: ResizeToIntMult
      mult_int: 32
    - type: Normalize
  mode: val
  get_trimap: False

model:
  type: MODNet
  backbone:
    type: MobileNetV2
    pretrained: https://paddleseg.bj.bcebos.com/matting/models/MobileNetV2_pretrained/model.pdparams
  pretrained: Null

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PiecewiseDecay
  boundaries: [40000, 80000]
  values: [0.02, 0.002, 0.0002]
```

**Comment by zhenzi0322** [comment]
> ![image](https://user-images.githubusercontent.com/30919197/168941864-6fe56013-dc95-4356-a38b-c47806da798f.png) 把这一行删除就行了

您好，可能`Matting`模型本身就存在抠出来的图片边缘不清晰的问题，我通过下载`PP-Matting-512`和`PP-Matting-1024`的模型下来进行预测同一张图片发现这两个模型的边缘都比较清晰。我想知道什么时候可以开源`PP-Matting-512`和`PP-Matting-1024`。我这边想尝试使用这两个模型进行训练。

**Comment by wuyefeilin** [comment]
可以把MODNet的backbone换成hrnet， 这样模型的学习能力会更强。 因为训练的时候是小图，在大图中预测容易出现错误的情况。 你把512改成1024重新预测试试。

另外你的数据集的分辨率分布情况是怎么样的？

**Comment by zhenzi0322** [comment]
> 另外你的数据集的分辨率分布情况是怎么样的？

有大图也有小图，小图最小是`550*366`，大图的话最大达到4K。我是把它们全部放在一起训练的。

**Comment by zhenzi0322** [comment]
> 可以把MODNet的backbone换成hrnet， 这样模型的学习能力会更强。 因为训练的时候是小图，在大图中预测容易出现错误的情况。 你把512改成1024重新预测试试。

好的，我试试您说的这种方式重新预测看看。

**Comment by zhenzi0322** [comment]
> > 可以把MODNet的backbone换成hrnet， 这样模型的学习能力会更强。 因为训练的时候是小图，在大图中预测容易出现错误的情况。 你把512改成1024重新预测试试。
> 
> 好的，我试试您说的这种方式重新预测看看。

我按您说的重新修改了配置文件，配置文件内容如下：
```yaml
batch_size: 16
iters: 200000

train_dataset:
  type: MattingDataset
  dataset_root: data/PPM-100
  train_file: train.txt
  transforms:
    - type: LoadImages
    - type: ResizeByShort
      short_size: 1024
    - type: RandomCrop
      crop_size: [1024, 1024]
    - type: RandomDistort
    - type: RandomBlur
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: MattingDataset
  dataset_root: data/PPM-100
  val_file: val.txt
  transforms:
    - type: LoadImages
    - type: ResizeByShort
      short_size: 1024
    - type: ResizeToIntMult
      mult_int: 32
    - type: Normalize
  mode: val
  get_trimap: False

model:
  type: MODNet
  backbone:
    type: HRNet_W18
    pretrained: https://paddleseg.bj.bcebos.com/matting/models/MobileNetV2_pretrained/model.pdparams
  pretrained: Null

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PiecewiseDecay
  boundaries: [40000, 80000]
  values: [0.02, 0.002, 0.0002]
```
然后我使用我之前训练好的模型跟这个配置文件一起进行导出模型。最后预测的效果如下：
![image](https://user-images.githubusercontent.com/34839719/169438998-b3ee3156-d3c6-4ce2-b4cd-25276774374f.png)

上面图片的尺寸是`3264*1836`。抠得效果不太好。

**Comment by wuyefeilin** [comment]
![image](https://user-images.githubusercontent.com/30919197/169468706-60d39f9a-7316-4bee-ae74-5d55bd3fe490.png)
这个改成
-type: LimitShort
  max_short:1024

**Comment by zhenzi0322** [comment]
> ![image](https://user-images.githubusercontent.com/30919197/169468706-60d39f9a-7316-4bee-ae74-5d55bd3fe490.png) 这个改成 -type: LimitShort max_short:1024

是不是得配合采用`HRNet_W18`训练的模型进行导出才会效果好，我试了如果用我之前的模型配合你说的参数进行抠图，抠得效果会很差。

**Comment by wuyefeilin** [comment]
是的， 或者重新训练一下看看

**Comment by zhenzi0322** [comment]
> 是的， 或者重新训练一下看看

我已经重新训练好了一个模型，预测发现边缘的清晰度是有点好转，但是边缘的清晰还是不够。 请问有没有其他更好的解决办法呢？尽量让抠出来的图的边缘清晰度跟原图接近。

**Comment by wuyefeilin** [comment]
麻烦展示一下效果

要跟原图清晰度一致，需要保持原图分辨率进行预测，但图片过大会降低语义预测的正确性。需要进行trade off

**Comment by zhenzi0322** [comment]
> 麻烦展示一下效果
> 
> 要跟原图清晰度一致，需要保持原图分辨率进行预测，但图片过大会降低语义预测的正确性。需要进行trade off

![b471283a9de741fcb57ae6c47f54a88a](https://user-images.githubusercontent.com/34839719/170940020-1dfbc845-045e-48d1-b751-14ddb7db4eac.png)

**Comment by zhenzi0322** [comment]
> 麻烦展示一下效果
> 
> 要跟原图清晰度一致，需要保持原图分辨率进行预测，但图片过大会降低语义预测的正确性。需要进行trade off

![image](https://user-images.githubusercontent.com/34839719/170940283-b31531a6-dcbd-404a-8e1f-de336fe68221.png)


如何进行trade off ？

**Comment by wuyefeilin** [comment]
![image](https://user-images.githubusercontent.com/30919197/170941222-be3523a2-9072-4e21-9cf3-677aefbf57d7.png)
调节数值控制图片大小上限
之前去除，所有图片进行原图预测

**Comment by wuyefeilin** [comment]
> > ![image](https://user-images.githubusercontent.com/30919197/169468706-60d39f9a-7316-4bee-ae74-5d55bd3fe490.png) 这个改成 -type: LimitShort max_short:1024
> 
> 是不是得配合采用`HRNet_W18`训练的模型进行导出才会效果好，我试了如果用我之前的模型配合你说的参数进行抠图，抠得效果会很差。

修改val_dataset下LimitShort的max_short的数值控制图片大小上限， 或者直接去除LimitShort进行原图预测。

**Comment by zhenzi0322** [comment]
> 麻烦展示一下效果
> 
> 要跟原图清晰度一致，需要保持原图分辨率进行预测，但图片过大会降低语义预测的正确性。需要进行trade off

我通过把抠图的图像拖入到`photoshop`中查看，发现好像有一层比较淡的白色叠在了抠图图像的上面造成了抠图图像的模糊。

如下：
![demodemo](https://user-images.githubusercontent.com/34839719/170943354-7e039529-f880-4c62-83ea-6d1acf591ca3.gif)

**Comment by zhenzi0322** [comment]
> > > ![image](https://user-images.githubusercontent.com/30919197/169468706-60d39f9a-7316-4bee-ae74-5d55bd3fe490.png) 这个改成 -type: LimitShort max_short:1024
> > 
> > 
> > 是不是得配合采用`HRNet_W18`训练的模型进行导出才会效果好，我试了如果用我之前的模型配合你说的参数进行抠图，抠得效果会很差。
> 
> 修改val_dataset下LimitShort的max_short的数值控制图片大小上限， 或者直接去除LimitShort进行原图预测。

这个我刚试了，我的配置文件如下：
```yaml
Deploy:
  model: model.pdmodel
  params: model.pdiparams
  transforms:
  - type: LoadImages
  - mult_int: 32
    type: ResizeToIntMult
  - type: Normalize
```

预测效果如下所示：
![image](https://user-images.githubusercontent.com/34839719/170943945-739b5ff5-7e40-4bdf-86d8-9991f691c711.png)

效果不好，难道又得重新训练才行？

**Comment by wuyefeilin** [comment]
这也是modnet算法的局限性了，在过大分辨率图像中容易引起语义预测的不正确

**Comment by zhenzi0322** [comment]
> 这也是modnet算法的局限性了，在过大分辨率图像中容易引起语义预测的不正确

是不是说明目前已经达到最好的效果了？

**Comment by wuyefeilin** [comment]
最好能弄个验证集进行判断

**Comment by zhenzi0322** [comment]
> 最好能弄个验证集进行判断

验证集是有的，请问这个验证集怎么判断出来呢？

**Comment by zhenzi0322** [comment]
> 最好能弄个验证集进行判断

下面是我通过评估出来的：
![image](https://user-images.githubusercontent.com/34839719/171079568-f95d4fa8-a1f8-4649-ab05-54000048fb38.png)

评估出来的结果如何看出效果呢？

**Comment by wuyefeilin** [comment]
![image](https://user-images.githubusercontent.com/30919197/171082572-3675632d-978f-4f47-96b5-bcb03c9770ba.png)
这个指标越低表示跟ground truth越接近，扣图质量越好。

**Comment by zhenzi0322** [comment]
> ![image](https://user-images.githubusercontent.com/30919197/171082572-3675632d-978f-4f47-96b5-bcb03c9770ba.png) 这个指标越低表示跟ground truth越接近，扣图质量越好。

好的，请问是主要看SAD还是MSE呢？

**Comment by zhenzi0322** [comment]
> > ![image](https://user-images.githubusercontent.com/30919197/171082572-3675632d-978f-4f47-96b5-bcb03c9770ba.png) 这个指标越低表示跟ground truth越接近，扣图质量越好。
> 
> 好的，请问是主要看SAD还是MSE呢？

我把验证集的量加大后，指标又变大了。如下：
![image](https://user-images.githubusercontent.com/34839719/171084075-872818f3-9c08-476f-b8a5-a6c354fa30ec.png)

**Comment by wuyefeilin** [comment]
两者指标都可以对比的。
16张有点小了，可以多弄点，至少弄个50张吧， 这样用来迭代模型比较准

**Comment by zhenzi0322** [comment]
> 两者指标都可以对比的。 16张有点小了，可以多弄点，至少弄个50张吧， 这样用来迭代模型比较准

好的

**Comment by zhenzi0322** [comment]
> 两者指标都可以对比的。 16张有点小了，可以多弄点，至少弄个50张吧， 这样用来迭代模型比较准

配置文件：
```yml
batch_size: 16
iters: 100000

train_dataset:
  type: MattingDataset
  dataset_root: data/2000
  train_file: train.txt
  transforms:
    - type: LoadImages
    - type: LimitShort
      max_short: 1024
    - type: RandomCrop
      crop_size: [1024, 1024]
    - type: RandomDistort
    - type: RandomBlur
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: MattingDataset
  dataset_root: data/2000
  val_file: val.txt
  transforms:
    - type: LoadImages
    - type: LimitShort
      max_short: 1024
    - type: ResizeToIntMult
      mult_int: 32
    - type: Normalize
  mode: val
  get_trimap: False

model:
  type: MODNet
  backbone:
    type: HRNet_W18
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  pretrained: Null

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PiecewiseDecay
  boundaries: [40000, 80000]
  values: [0.02, 0.002, 0.0002]
```

这样的配置文件训练模型好像一直没有打印出日志出来。

**Comment by wuyefeilin** [comment]
给一下报错信息，如果是显存问题，可以减小batch_size

**Comment by zhenzi0322** [comment]
> 给一下报错信息，如果是显存问题，可以减小batch_size

没有任何的报错信息，就是一直如下图所示：
![image](https://user-images.githubusercontent.com/34839719/171319247-cde28eab-d9ec-4f52-9c8b-b8e4c6cdfbfb.png)

显存是够的。我如果修改了如下：
```
batch_size: 16
iters: 200000

train_dataset:
  type: MattingDataset
  dataset_root: data/2000
  train_file: train.txt
  transforms:
    - type: LoadImages
    - type: ResizeByShort
      short_size: 1024
    - type: RandomCrop
      crop_size: [1024, 1024]
    - type: RandomDistort
    - type: RandomBlur
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: MattingDataset
  dataset_root: data/2000
  val_file: val.txt
  transforms:
    - type: LoadImages
    - type: ResizeByShort
      short_size: 1024
    - type: ResizeToIntMult
      mult_int: 32
    - type: Normalize
  mode: val
  get_trimap: False

model:
  type: MODNet
  backbone:
    type: HRNet_W18
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  pretrained: Null

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PiecewiseDecay
  boundaries: [40000, 80000]
  values: [0.02, 0.002, 0.0002]
```
像上面的配置它又可以正常训练了。可以打印出每次的迭代。
