### ISSUE TITLE
[General Issue] PP-LiteSeg效果与deeplabv3p相差大,有没有好的改进方法

### ISSUE THREAD

**Issue by x12901** [PaddlePaddle/PaddleSeg#2318]
我尝试在我的数据集上训练deeplabv3p取得很好的效果搭配LovaszSoftmaxLoss, mIoU可以达到0.69,为了缩短检测时间,我尝试使用PP-LiteSeg,但是效果并不理想,搭配LovaszSoftmaxLoss,mIoU最好的结果只有0.54,按照论文来看应该是有0.02的差距才对,PP-LiteSeg有没有更好的精度提升方法
pp_liteseg_stdc2_cityscapes_1024x512_scale1.0_160k.yml
```
_base_: './pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.yml'

train_dataset:
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: Normalize
  mode: train

test_config:
  aug_eval: True
  scales: 1.0

model:
  _inherited_: False
  type: PPLiteSeg
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz

train_dataset:
  type: Dataset
  dataset_root: data/test
  train_path: data/test/train.txt
  num_classes: 6
  mode: train

val_dataset:
  type: Dataset
  dataset_root: data/test
  val_path: data/test/val.txt
  num_classes: 6
  mode: val

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 130000
    - type: DiceLoss
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
  coef: [1, 1, 1]
```
deeplabv3p_resnet50_os8_cityscapes_1024x512_80k_rmiloss.yml
```
_base_: 'deeplabv3p_resnet50_os8_cityscapes_1024x512_80k.yml'

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
      
train_dataset:
  type: Dataset
  dataset_root: data/test
  train_path: data/test/train.txt
  num_classes: 6
  mode: train

val_dataset:
  type: Dataset
  dataset_root: data/test
  val_path: data/test/val.txt
  num_classes: 6
  mode: val

```
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：

    PaddleSeg版本：PaddleSeg release/2.5
    PaddlePaddle版本：PaddlePaddle 2.3
    操作系统信息：Windows
    Python版本号：Python3.8
    CUDA/cuDNN版本：Driver API Version: 11.1, Runtime API Version: 10.2,cuDNN Version: 7.6.
