### ISSUE TITLE
[General Issue] bankbone修改之后，似乎出现了问题，分割图像时出现了，像素点错乱

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2391]
pspnet 

修改如下：
model:
  type: PSPNet
  backbone:
    type: MobileNetV3_large_x1_0
    pretrained: https://paddleseg.bj.bcebos.com/dygraph/backbone/mobilenetv3_large_x1_0_ssld.tar.gz
  backbone_indices: [1, 3]
  pp_out_channels: 1024
  bin_sizes: [1, 2, 3, 6]
  enable_auxiliary_loss: True
  align_corners: False
  pretrained: null

但是效果出现了问题，出现了像素点分割散乱，是不是配置存在没有对上的问题，但是代码它能够正常训练，能看一下是哪里出现了问题嘛

**Comment by juncaipeng** [comment]
主要是替换了Backbone后，原先MobileNetV3_large_x1_0最终的输出是32倍下采样。建议改为：
```
backbone:
  type: MobileNetV3_large_x1_0_os8
  pretrained: https://paddleseg.bj.bcebos.com/dygraph/backbone/mobilenetv3_large_x1_0_ssld.tar.gz
backbone_indices: [2, 3]
pp_out_channels: 1024
bin_sizes: [1, 2, 3, 6]
enable_auxiliary_loss: True
align_corners: False
pretrained: null
```

此外，建议直接试用超轻量级分割模型：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/README_CN.md#-%E4%BA%A7%E4%B8%9A%E7%BA%A7%E5%88%86%E5%89%B2%E6%A8%A1%E5%9E%8B%E5%BA%93
