### ISSUE TITLE
Could you please share the configs of HRNet cityscapes?

### ISSUE THREAD

**Issue by nigyiii** [PaddlePaddle/PaddleSeg#245]
Hi, i found it hard to reproduce the results on cityscapes using HRNet w48. I trained the model with train set and mIoU is only about 70% on validation set. Can you share the config file(.yaml) of HRNet cityscapes?

**Comment by nigyiii** [comment]
Below is my config.
这是我的配置
```
DATASET:
    DATA_DIR: "./dataset/cityscapes/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 19
    TEST_FILE_LIST: "dataset/cityscapes/test.list"
    TRAIN_FILE_LIST: "dataset/cityscapes/train.list"
    VAL_FILE_LIST: "dataset/cityscapes/val.list"
    IGNORE_INDEX: 255

# 预训练模型配置
MODEL:
    MODEL_NAME: "hrnet"
    DEFAULT_NORM_TYPE: "bn"
    HRNET:
        STAGE2:
            NUM_CHANNELS: [48, 96]
        STAGE3:
            NUM_CHANNELS: [48, 96, 192]
        STAGE4:
            NUM_CHANNELS: [48, 96, 192, 384]

# 其他配置
TRAIN_CROP_SIZE: (1024, 512)
EVAL_CROP_SIZE: (1024, 512)
AUG:
    FIX_RESIZE_SIZE: (1024, 512)
    MIRROR: True
BATCH_SIZE: 12
TRAIN:
    PRETRAINED_MODEL_DIR: "./pretrained_model/HRNet_W48_C_pretrained/"
    MODEL_SAVE_DIR: "./saved_model/hrnet_cityscapes_w48_train/"
    SNAPSHOT_EPOCH: 5
    # 是否使用多卡间同步BatchNorm均值和方差
    SYNC_BATCH_NORM: True
TEST:
    TEST_MODEL: "./saved_model/hrnet_cityscapes_w48_train/final"
SOLVER:
    NUM_EPOCHS: 100
    LR: 0.01
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    # 动量参数
    MOMENTUM: 0.9
    # 学习率权重衰减，0-1
    WEIGHT_DECAY: 0.0005
```

**Comment by wuyefeilin** [comment]
@nigyiii 
按照下面试一下：
```
DATASET:
    DATA_DIR: "./dataset/cityscapes/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 19
    TEST_FILE_LIST: "dataset/cityscapes/test.list"
    TRAIN_FILE_LIST: "dataset/cityscapes/train.list"
    VAL_FILE_LIST: "dataset/cityscapes/val.list"
    IGNORE_INDEX: 255

# 预训练模型配置
MODEL:
    MODEL_NAME: "hrnet"
    DEFAULT_NORM_TYPE: "bn"
    HRNET:
        STAGE2:
            NUM_CHANNELS: [48, 96]
        STAGE3:
            NUM_CHANNELS: [48, 96, 192]
        STAGE4:
            NUM_CHANNELS: [48, 96, 192, 384]

# 其他配置
TRAIN_CROP_SIZE: (1024, 512)
EVAL_CROP_SIZE: (2048, 1024)
AUG:
    AUG_METHOD: 'stepscaling
    MIRROR: True
BATCH_SIZE: 12
TRAIN:
    PRETRAINED_MODEL_DIR: "./pretrained_model/HRNet_W48_C_pretrained/"
    MODEL_SAVE_DIR: "./saved_model/hrnet_cityscapes_w48_train/"
    SNAPSHOT_EPOCH: 5
    # 是否使用多卡间同步BatchNorm均值和方差
    SYNC_BATCH_NORM: True
TEST:
    TEST_MODEL: "./saved_model/hrnet_cityscapes_w48_train/final"
SOLVER:
    NUM_EPOCHS: 500
    LR: 0.01
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    # 动量参数
    MOMENTUM: 0.9
    # 学习率权重衰减，0-1
    WEIGHT_DECAY: 0.0005
```
