### ISSUE TITLE
Model performance significantly worse between predict.py and infer.py

### ISSUE THREAD

**Issue by tarun-msd** [PaddlePaddle/PaddleSeg#2495]
Hey, I've trained my modnet matting model using PaddleSeg, and I tried using both predict.py and infer.py to perform inference.
predict.py gives accurate, very clean outputs. I want to deploy the model so I ran export.py with the config and created an inference model. Now, when I use infer.py to get inference outputs of my model, the predicted images look very poor. 
The val_transforms have been copied over directly from the original config in my deploy.yaml config. Its passing the same transforms to both predict.py and infer.py. What is causing this?

Oriignal Prediction (predict.py): 
![image](https://user-images.githubusercontent.com/97960833/187399782-78a47170-601c-4619-a8b4-4360eff5b47d.png)

Infer.py prediction:
![image](https://user-images.githubusercontent.com/97960833/187399397-07a2723b-62cd-4338-bf85-cdfa1bc3ede5.png)

**Comment by wuyefeilin** [comment]
When you export the model, it will generate a deploy.yaml which can be used in infer.py without any procession.

**Comment by tarun-msd** [comment]
@wuyefeilin Yeah I'm aware of that, I used deploy.yaml as my config for infer.py. My problem is there's a significant difference in prediction quality as shown above between using predict.py and infer.py. 
Can you help me understand why that's happening?

**Comment by wuyefeilin** [comment]
Do you change the code? If yes, change the code detailedly. If not, can you give me the model before and after export.

**Comment by tarun-msd** [comment]
No I did not change the code anywhere. 

[Google Drive Folder](https://drive.google.com/drive/folders/12q-KBBJFvfx77dcrqI2H2p1dcxcKRrQs?usp=sharing)

Folder contains two zip files : Before exporting and after exporting, with their config files.

**Comment by tarun-msd** [comment]
Hi @wuyefeilin any idea why this is happening?

**Comment by wuyefeilin** [comment]
Give me your exporting command

**Comment by tarun-msd** [comment]
```python export.py --config configs/modnet/modnet-hrnet_w18-iter19_1.yml --save_dir deploy/models/iter19_1 --model_path train_runs/iter19_1/iter_60000/model.pdparams ```


This is my config 
```
batch_size: 8
iters: 100000

train_dataset:
  type: MattingDataset
  dataset_root: <my_dataset>
  train_file: train.txt
  transforms:
    - type: LoadImages
    - type: Resize
      target_size: [512, 512]
    - type: RandomDistort
    - type: RandomBlur
    - type: RandomNoise
    - type: RandomSharpen
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: MattingDataset
  dataset_root: <my_dataset>
  val_file: val.txt
  transforms:
    - type: LoadImages
    - type: ResizeByShort
      short_size: 512
    - type: ResizeToIntMult
      mult_int: 32
    - type: Normalize
  mode: val
  get_trimap: False

model:
  type: MODNet
  backbone:
    type: HRNet_W18
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  pretrained: Null

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PiecewiseDecay
  boundaries: [40000, 80000]
  values: [0.01, 0.001, 0.0001]

```
