### ISSUE TITLE
How to Predict VocDataset val.txt Datasets Only?

### ISSUE THREAD

**Issue by YoungjaeDev** [PaddlePaddle/PaddleSeg#3056]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Hi! I set it as below and trained with pplite_seg to get the best_model. 
But I'm curious about the image of Val.txt through predict, but I do not know how to put the parameters.

```yaml
val_dataset
   type: PascalVOC
   dataset_root: data/VOCdevkit/
   mode: val
```
I am currently using Release 2.6 docker.

```bash
python predict.py ~~~~ --image_path data/VOCdevkit/VOC2012/JPEGImage
```
