### ISSUE TITLE
关于使用Unetr时数据和标签的输入尺寸问题

### ISSUE THREAD

**Issue by SurvivorNo1** [PaddlePaddle/PaddleSeg#3069]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我想使用自己的数据集在Unetr上训练，我的数据集算上背景有16类，是.nii.gz类型的CT数据。我将数据处理成（1,128,128,128），标签处理成（1，128，128，128），模型不能正常运行。提示
`SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception. [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)`
然后，我将数据处理成（128,128,128），标签处理成（128，128，128），模型也不能正常运行，提示也一样。

我的配置文件如下：
```
data_root: /home/aistudio/Amos2022
batch_size: 4
iters: 30000

data_root: /home/aistudio/Amos2022
batch_size: 4
iters: 30000


train_dataset:
  type: msd_brain_dataset
  dataset_root: phase0/
  result_dir: phase0/labels
  num_classes: 16
  transforms: 
    - type: RandomRotation4D
      degrees: 90
      rotate_planes: [[1, 2], [1, 3],[2, 3]]
    - type: RandomFlip4D
      flip_axis: [1,2,3]
      prob: 0.1
  mode: train


val_dataset:
  type: msd_brain_dataset
  dataset_root: phase0/
  result_dir: phase0/labels
  num_classes: 16
  transforms: []
  mode: val
  dataset_json_path: "/home/aistudio/Amos2022/raw/dataset.json"


test_dataset:
  type: msd_brain_dataset
  dataset_root: phase0/
  result_dir: phase0/labels
  num_classes: 16
  transforms: []
  mode: test
  dataset_json_path: "/home/aistudio/Amos2022/raw/dataset.json"

optimizer:
  type: AdamW
  weight_decay: 1.0e-4

lr_scheduler:
  type: PolynomialDecay
  decay_steps: 30000
  learning_rate: 0.0001
  end_lr: 0
  power: 0.9


loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
          weight: Null
        - type: DiceLoss
      coef: [1, 1]
  coef: [1]

model:
  type: UNETR
  img_shape: (128, 128, 128)
  in_channels: 1
  num_classes: 16
  embed_dim: 768
  patch_size: 16
  num_heads: 12
  dropout: 0.1
train_dataset:
  type: msd_brain_dataset
  dataset_root: phase0/
  result_dir: phase0/labels
  num_classes: 16
  transforms: 
    - type: RandomRotation4D
      degrees: 90
      rotate_planes: [[1, 2], [1, 3],[2, 3]]
    - type: RandomFlip4D
      flip_axis: [1,2,3]
      prob: 0.1
  mode: train


val_dataset:
  type: msd_brain_dataset
  dataset_root: phase0/
  result_dir: phase0/labels
  num_classes: 16
  transforms: []
  mode: val
  dataset_json_path: "/home/aistudio/Amos2022/raw/dataset.json"


test_dataset:
  type: msd_brain_dataset
  dataset_root: phase0/
  result_dir: phase0/labels
  num_classes: 16
  transforms: []
  mode: test
  dataset_json_path: "/home/aistudio/Amos2022/raw/dataset.json"

optimizer:
  type: AdamW
  weight_decay: 1.0e-4

lr_scheduler:
  type: PolynomialDecay
  decay_steps: 30000
  learning_rate: 0.0001
  end_lr: 0
  power: 0.9


loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
          weight: Null
        - type: DiceLoss
      coef: [1, 1]
  coef: [1]

model:
  type: UNETR
  img_shape: (128, 128, 128)
  in_channels: 1
  num_classes: 16
  embed_dim: 768
  patch_size: 16
  num_heads: 12
  dropout: 0.1
```

**Comment by zhaoyantao-murray** [comment]
您提供一下训练命令和原yml配置文件的路径哈

**Comment by SurvivorNo1** [comment]
> 您提供一下训练命令和原yml配置文件的路径哈

很感谢您的回复：
下面是我在notebook中的训练命令：
```
%cd  ~/PaddleSeg/contrib/MedicalSeg
!python train.py --config configs/msd_brain_seg/unetr_msd_brain_seg_1e-4.yml \
                 --do_eval --save_interval 1000 --has_dataset_json False --is_save_data False --num_workers 4 --log_iters 10 --use_vdl
```
下面是我的yml文件路径
`/home/aistudio/PaddleSeg/contrib/MedicalSeg/configs/msd_brain_seg/unetr_msd_brain_seg_1e-4.yml`
下面是我的配置文件，和官方对比有修改，修改了
in_channels，num_classes，数据集路径，train_dataset的transforms
```
data_root: /tmp/Amos2022
batch_size: 4
iters: 30000


train_dataset:
  type: msd_brain_dataset
  dataset_root: phase0/
  result_dir: phase0/labels
  num_classes: 16
  transforms: 
    - type: RandomRotation4D
      degrees: 90
      rotate_planes: [[1, 2], [1, 3],[2, 3]]
    - type: RandomFlip4D
      flip_axis: [1,2,3]
      prob: 0.1
  mode: train


val_dataset:
  type: msd_brain_dataset
  dataset_root: phase0/
  result_dir: phase0/labels
  num_classes: 16
  transforms: []
  mode: val
  dataset_json_path: "/tmp/Amos2022/raw/dataset.json"


test_dataset:
  type: msd_brain_dataset
  dataset_root: phase0/
  result_dir: phase0/labels
  num_classes: 16
  transforms: []
  mode: test
  dataset_json_path: "/tmp/Amos2022/raw/dataset.json"

optimizer:
  type: AdamW
  weight_decay: 1.0e-4

lr_scheduler:
  type: PolynomialDecay
  decay_steps: 30000
  learning_rate: 0.0001
  end_lr: 0
  power: 0.9


loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
          weight: Null
        - type: DiceLoss
      coef: [1, 1]
  coef: [1]

model:
  type: UNETR
  img_shape: (128, 128, 128)
  in_channels: 1
  num_classes: 16
  embed_dim: 768
  patch_size: 16
  num_heads: 12
  dropout: 0.1
```
