### ISSUE TITLE
关于swinunet模型训练的问题

### ISSUE THREAD

**Issue by iyangiii** [PaddlePaddle/PaddleSeg#3071]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在训练swinunet模型时 添加了do_eval参数 do_eval出的数据中mdice有很多个0 当我使用原数据集去跑的时候 也出现了非常多0 原数据集都跑不通不太对劲吧？  第一张图是我用原数据集跑的结果 第二张图是用自己数据集跑的结果
![image](https://user-images.githubusercontent.com/101607550/225819050-2a9953a3-9da5-4166-bf4c-9ad7976af1a7.png)
![0555e7fdf3ec3518bb6d5ae265f9163](https://user-images.githubusercontent.com/101607550/225819181-cc209bb8-8bf8-43bc-96da-50971453d5db.png)

**Comment by zhaoyantao-murray** [comment]
请提供训练命令和所使用的yml配置文件路径

**Comment by iyangiiiii** [comment]
以下是我训练自己数据集的训练命令以及配置文件
%cd ~/PaddleSeg/contrib/MedicalSeg/
!python train.py --config configs/synapse/swinunet_abdomen_224_224_1_14k_5e-2.yml \
 --do_eval --save_interval 1000 --has_dataset_json False --is_save_data False \
  --num_workers 4 --log_iters 50 --use_vdl

_base_: '../_base_/global_configs.yml'

train_dataset:
  type: Abdomen
  dataset_root: abdomen/abdomen_phase0
  result_dir: abdomen/abdomen_phase1
  transforms:
    - type: RandomFlip3D
      flip_axis: [1, 2]
    - type: RandomQuarterTurn3D
      rotate_planes: [[ 1, 2 ]]
    - type: RandomRotation3D
      degrees: 20
      rotate_planes: [[1, 2]]
    - type: Resize3D
      size: [1, 224, 224]
  mode: train
  num_classes: 15

val_dataset:
  type: Abdomen
  dataset_root: abdomen/abdomen_phase0
  result_dir: abdomen/abdomen_phase1
  num_classes: 15
  transforms:
    - type: Resize3D
      size: [1, 224, 224]
  mode: val
  dataset_json_path: data/abdomen/abdomen_raw/dataset.json

test_dataset:
  type: Abdomen
  dataset_root:  abdomen/abdomen_phase0
  result_dir:  abdomen/abdomen_phase1
  num_classes: 15
  transforms:
    - type: Resize3D
      size: [1, 224, 224]
  mode: val
  dataset_json_path: data/abdomen/abdomen_raw/dataset.json

_base_: 'abdomen.yml'

batch_size: 16
iters: 30000

model:
  type: SwinUNet
  backbone:
    type: SwinTransformer_tinier_patch4_window7_224
  num_classes: 16
  pretrained: https://paddleseg.bj.bcebos.com/paddleseg3d/synapse/abdomen/swinunet_abdomen_224_224_1_14k_5e-2/swinunet_pretrained.zip

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 1.0e-4

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.001
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: DiceLoss
      coef: [0.4, 0.6]
  coef: [1]

export:
  transforms:
    - type: Resize3D
      size: [ 1 ,224, 224 ]
  inference_helper:
    type: InferenceHelper2D

训练自带数据集时没有做过任何更改 yml路径为/home/aistudio/PaddleSeg/contrib/MedicalSeg/configs/synapse/swinunet_abdomen_224_224_1_14k_5e-2.yml
训练命令不变

**Comment by iyangiii** [comment]
> 请提供训练命令和所使用的yml配置文件路径

以下是我训练自己数据集的训练命令以及配置文件
%cd ~/PaddleSeg/contrib/MedicalSeg/
!python train.py --config configs/synapse/swinunet_abdomen_224_224_1_14k_5e-2.yml
--do_eval --save_interval 1000 --has_dataset_json False --is_save_data False
--num_workers 4 --log_iters 50 --use_vdl

base: '../base/global_configs.yml'

train_dataset:
type: Abdomen
dataset_root: abdomen/abdomen_phase0
result_dir: abdomen/abdomen_phase1
transforms:
- type: RandomFlip3D
flip_axis: [1, 2]
- type: RandomQuarterTurn3D
rotate_planes: [[ 1, 2 ]]
- type: RandomRotation3D
degrees: 20
rotate_planes: [[1, 2]]
- type: Resize3D
size: [1, 224, 224]
mode: train
num_classes: 15

val_dataset:
type: Abdomen
dataset_root: abdomen/abdomen_phase0
result_dir: abdomen/abdomen_phase1
num_classes: 15
transforms:
- type: Resize3D
size: [1, 224, 224]
mode: val
dataset_json_path: data/abdomen/abdomen_raw/dataset.json

test_dataset:
type: Abdomen
dataset_root: abdomen/abdomen_phase0
result_dir: abdomen/abdomen_phase1
num_classes: 15
transforms:
- type: Resize3D
size: [1, 224, 224]
mode: val
dataset_json_path: data/abdomen/abdomen_raw/dataset.json

base: 'abdomen.yml'

batch_size: 16
iters: 30000

model:
type: SwinUNet
backbone:
type: SwinTransformer_tinier_patch4_window7_224
num_classes: 16
pretrained: https://paddleseg.bj.bcebos.com/paddleseg3d/synapse/abdomen/swinunet_abdomen_224_224_1_14k_5e-2/swinunet_pretrained.zip

optimizer:
type: sgd
momentum: 0.9
weight_decay: 1.0e-4

lr_scheduler:
type: PolynomialDecay
learning_rate: 0.001
end_lr: 0
power: 0.9

loss:
types:
- type: MixedLoss
losses:
- type: CrossEntropyLoss
- type: DiceLoss
coef: [0.4, 0.6]
coef: [1]

export:
transforms:
- type: Resize3D
size: [ 1 ,224, 224 ]
inference_helper:
type: InferenceHelper2D

训练自带数据集时没有做过任何更改 yml路径为/home/aistudio/PaddleSeg/contrib/MedicalSeg/configs/synapse/swinunet_abdomen_224_224_1_14k_5e-2.yml
训练命令不变

**Comment by SurvivorNo1** [comment]
> 请提供训练命令和所使用的yml配置文件路径
下面是我的训练命令:
`%cd  ~/PaddleSeg/contrib/MedicalSeg
!python train.py --config configs/msd_brain_seg/unetr_msd_brain_seg_1e-4.yml \
                 --do_eval --save_interval 1000 --has_dataset_json False --is_save_data False --num_workers 4 --log_iters 10 --use_vdl`
下面是我的yml配置文件路径：
`/home/aistudio/PaddleSeg/contrib/MedicalSeg/configs/msd_brain_seg/unetr_msd_brain_seg_1e-4.yml`
下面是我的配置文件：
```
data_root: /tmp/Amos2022
batch_size: 4
iters: 30000


train_dataset:
  type: msd_brain_dataset
  dataset_root: phase0/
  result_dir: phase0/labels
  num_classes: 16
  transforms: 
    - type: RandomRotation4D
      degrees: 90
      rotate_planes: [[1, 2], [1, 3],[2, 3]]
    - type: RandomFlip4D
      flip_axis: [1,2,3]
      prob: 0.1
  mode: train


val_dataset:
  type: msd_brain_dataset
  dataset_root: phase0/
  result_dir: phase0/labels
  num_classes: 16
  transforms: []
  mode: val
  dataset_json_path: "/tmp/Amos2022/raw/dataset.json"


test_dataset:
  type: msd_brain_dataset
  dataset_root: phase0/
  result_dir: phase0/labels
  num_classes: 16
  transforms: []
  mode: test
  dataset_json_path: "/tmp/Amos2022/raw/dataset.json"

optimizer:
  type: AdamW
  weight_decay: 1.0e-4

lr_scheduler:
  type: PolynomialDecay
  decay_steps: 30000
  learning_rate: 0.0001
  end_lr: 0
  power: 0.9


loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
          weight: Null
        - type: DiceLoss
      coef: [1, 1]
  coef: [1]

model:
  type: UNETR
  img_shape: (128, 128, 128)
  in_channels: 1
  num_classes: 16
  embed_dim: 768
  patch_size: 16
  num_heads: 12
  dropout: 0.1
```
