### ISSUE TITLE
QualityInspector  'Config' object has no attribute 'model' 全流程预测报错

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#3203]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

分割评估模型 正常
`python tools/seg/val.py --config configs/seg/ocrnet/ocrnet_hrnetw18_RoI_defect_256x256_40k.yml --model_path D:/0SDXX/PaddleSeg/contrib/QualityInspector/output/RoI/best_model/model.pdparams`

e2e_det.yml  没问题

e2e_det_RoI_seg.yml
e2e_seg.yml
有问题

但是我的模型都训练好了
而且还写的是绝对路径
检测不知道为什么报错

---------------------------

全流程预测报错
`python tools/end2end/predict.py --config ./configs/end2end/e2e_det_RoI_seg.yml --input F:\Magnetic-tile-defect-datasets_OUT\images\val/ --output_dir ./output_det_roi/`

```

args:  Namespace(config='./configs/end2end/e2e_det_RoI_seg.yml', device='gpu', input='F:\\Magnetic-tile-defect-datasets_OUT\\images\\val/', opt={}, output_dir='./output_det_roi/')
env_cfg:  {'device': 'gpu', 'output_dir': './output_det_roi/', 'save': True, 'visualize': False, 'opt': {}, 'config': './configs/end2end/e2e_det_RoI_seg.yml', 'input': 'F:\\00Biaozhu\\Magnetic-tile-defect-datasets_OUT\\images\\val/'}
----------- Environment Arguments -----------
config: ./configs/end2end/e2e_det_RoI_seg.yml
device: gpu
input: F:\Magnetic-tile-defect-datasets_OUT\images\val/
opt: {}
output_dir: ./output_det_roi/
save: true
visualize: false

------------- Model Arguments ---------------
- Detection:
    config_path: D:/0SDXX/PaddleSeg/contrib/QualityInspector/configs/det/hrnet/faster_rcnn_hrnetv2p_w18_3x_defect.yml
    model_path: D:/0SDXX/PaddleSeg/contrib/QualityInspector/output/faster_rcnn_hrnetv2p_w18_3x_defect/model_final.pdparams
    score_threshold: 0.01
- CropSegmentation:
    aug_pred: true
    config_path: D:/0SDXX/PaddleSeg/contrib/QualityInspector/configs/seg/ocrnet/ocrnet_hrnetw18_RoI_defect_256x256_40k.yml
    model_path: D:/0SDXX/PaddleSeg/contrib/QualityInspector/output/RoI/best_model/model.pdparams
    pad_scale: 0.5
- PostProcess:
  - JudgeDetByScores:
      score_threshold:
        1: 0.1
        5: 0.2
  - JudgeByLengthWidth:
      len_thresh: 0
  - JudgeByArea:
      area_thresh:
        1: 10

---------------------------------------------
W0419 21:41:21.893710 25448 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.2
W0419 21:41:21.909473 25448 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
[04/19 21:41:23] ppdet.utils.checkpoint INFO: Finish loading model weights: D:/0SDXX/PaddleSeg/contrib/QualityInspector/output/faster_rcnn_hrnetv2p_w18_3x_defect/model_final.pdparams
Traceback (most recent call last):
  File "tools/end2end/predict.py", line 78, in <module>
    main()
  File "tools/end2end/predict.py", line 72, in main
    pipeline = Pipeline(args)
  File "D:\0SDXX\PaddleSeg\contrib\QualityInspector\qinspector\apis\pipeline.py", line 33, in __init__
    self.modules = Builder(self.model_cfg, self.env_cfg)
  File "D:\0SDXX\PaddleSeg\contrib\QualityInspector\qinspector\cvlib\framework.py", line 35, in __init__
    op = create(op_arch, op_cfg, env_cfg)
  File "D:\0SDXX\PaddleSeg\contrib\QualityInspector\qinspector\cvlib\workspace.py", line 47, in create
    return cls(model_cfg, env_cfg)
  File "D:\0SDXX\PaddleSeg\contrib\QualityInspector\qinspector\ops\segmentation.py", line 47, in __init__
    self.predictor = SegPredictor(seg_config, seg_model)
  File "D:\0SDXX\PaddleSeg\contrib\QualityInspector\qinspector\seg\engine\predictor.py", line 32, in __init__
    self.model = seg_config.model
AttributeError: 'Config' object has no attribute 'model'
```

ocrnet_hrnetw18_RoI_defect_256x256_40k.yml
```yml
batch_size: 32
iters: 1000

train_dataset:
  type: Dataset
  dataset_root: ./
  num_classes: 2
  train_path: F:/Magnetic-tile-defect-datasets_ROI/train/RoI.txt
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [256, 256]
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: ./
  num_classes: 2
  val_path: F:/Magnetic-tile-defect-datasets_ROI/val/RoI.txt
  transforms:
    - type: ResizeByLong
      long_size: 256
    - type: Normalize
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5


model:
  type: OCRNet
  backbone:
    type: HRNet_W18
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  num_classes: 2
  backbone_indices: [0]


lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.001
  end_lr: 0
  power: 0.9


loss:
  types:
    - type: DiceLoss
      weight: [0.4, 0.6]
    - type: DiceLoss
      weight: [0.4, 0.6]
  coef: [1, 0.4]

#loss:
#  types:
#    - type: CrossEntropyLoss
#      weight: [0.3, 0.7]
#    - type: CrossEntropyLoss
#      weight: [0.3, 0.7]
#  coef: [1, 0.4]

```

### 复现环境 Environment

win11
Python 3.8.16

----------

Package                Version       Editable project location
---------------------- ------------- -------------------------
aiofiles               23.1.0
aiohttp                3.8.4
aiosignal              1.3.1
albumentations         1.3.0
alembic                1.10.3
altair                 4.2.2
anyio                  3.6.2
astor                  0.8.1
async-timeout          4.0.2
attrdict               2.0.1
attrs                  23.1.0
Babel                  2.12.1
bce-python-sdk         0.8.83
Brotli                 1.0.9
certifi                2022.12.7
cffi                   1.15.1
charset-normalizer     3.1.0
click                  8.1.3
clickclick             20.10.2
colorama               0.4.6
connexion              2.14.2
contourpy              1.0.7
cycler                 0.11.0
Cython                 0.29.34
decorator              5.1.1
easydict               1.10
entrypoints            0.4
fastapi                0.95.1
ffmpy                  0.3.0
filelock               3.11.0
Flask                  2.2.3
flask-babel            3.1.0
Flask-Cors             3.0.10
flask-marshmallow      0.15.0
Flask-SQLAlchemy       3.0.3
fonttools              4.39.3
frozenlist             1.3.3
fsspec                 2023.4.0
future                 0.18.3
gevent                 22.10.2
geventhttpclient       2.0.2
gradio                 3.27.0
gradio_client          0.1.3
greenlet               2.0.2
grpcio                 1.53.0
h11                    0.14.0
httpcore               0.17.0
httpx                  0.24.0
huggingface-hub        0.13.4
idna                   3.4
imageio                2.27.0
importlib-metadata     6.4.1
importlib-resources    5.12.0
inflection             0.5.1
itsdangerous           2.1.2
Jinja2                 3.1.2
joblib                 1.2.0
jsonschema             4.17.3
kiwisolver             1.4.4
lap                    0.4.0
lazy_loader            0.2
linkify-it-py          2.0.0
llvmlite               0.39.1
Mako                   1.2.4
markdown-it-py         2.2.0
MarkupSafe             2.1.2
marshmallow            3.19.0
marshmallow-sqlalchemy 0.29.0
matplotlib             3.7.1
mdit-py-plugins        0.3.3
mdurl                  0.1.2
motmetrics             1.4.0
mpmath                 1.3.0
multidict              6.0.4
networkx               3.1
numba                  0.56.4
numpy                  1.23.5
onnx                   1.12.0
opencv-python          4.5.5.64
opencv-python-headless 4.7.0.72
opt-einsum             3.3.0
orjson                 3.8.10
packaging              23.1
paddle-bfloat          0.1.7
paddledet              2.6.0
paddlelabel            1.0.1
paddlepaddle-gpu       2.4.2.post112
paddleseg              2.8.0         d:\0sdxx\paddleseg
pandas                 2.0.0
Pillow                 9.5.0
pip                    23.0.1
pkgutil_resolve_name   1.3.10
prettytable            3.7.0
prompt-toolkit         3.0.38
protobuf               3.20.0
psutil                 5.9.5
pyclipper              1.3.0.post4
pycocotools            2.0.6
pycocotoolse           2.0.14
pycparser              2.21
pycryptodome           3.17
pydantic               1.10.7
pydub                  0.25.1
pyparsing              3.0.9
PyQt5                  5.15.9
PyQt5-Qt5              5.15.2
PyQt5-sip              12.12.0
pyrsistent             0.19.3
python-dateutil        2.8.2
python-multipart       0.0.6
python-rapidjson       1.10
pytz                   2023.3
PyWavelets             1.4.1
PyYAML                 6.0
QtPy                   2.3.1
qudida                 0.0.4
rarfile                4.0
requests               2.28.2
scikit-image           0.20.0
scikit-learn           1.2.2
scipy                  1.9.1
semantic-version       2.10.0
setuptools             66.0.0
shapely                2.0.1
six                    1.16.0
sklearn                0.0
sniffio                1.3.0
SQLAlchemy             2.0.9
starlette              0.26.1
sympy                  1.11.1
terminaltables         3.1.10
threadpoolctl          3.1.0
tifffile               2023.4.12
toolz                  0.12.0
tqdm                   4.65.0
tritonclient           2.32.0
typeguard              3.0.2
typing_extensions      4.5.0
tzdata                 2023.3
uc-micro-py            1.0.1
urllib3                1.26.15
uvicorn                0.21.1
visualdl               2.5.1
wcwidth                0.2.6
websockets             11.0.1
Werkzeug               2.2.3
wget                   3.2
wheel                  0.38.4
x2paddle               1.4.1
xmltodict              0.13.0
yarl                   1.8.2
zipp                   3.15.0
zope.event             4.6
zope.interface         6.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!
