### ISSUE TITLE
关于data_aug中rand_crop的问题，前景丢掉了

### ISSUE THREAD

**Issue by CeciliaPYY** [PaddlePaddle/PaddleSeg#322]
使用data_aug进行rand_crop时，应该是存在图片大小小于crop_size的情况，发生了前景丢失的问题。如下图所示，
![image](https://user-images.githubusercontent.com/30582437/88148801-bc218a80-cc31-11ea-8b67-68ef31e4c512.png)

config中的aug具体参数参考了另外一个yaml文件，如下所示
```
AUG:
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (488, 488) # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
    FLIP: False
    FLIP_RATIO: 0.2
    RICH_CROP:
        ENABLE: True
        ASPECT_RATIO: 0.0
        BLUR: False
        BLUR_RATIO: 0.1
        MAX_ROTATION: 0
        MIN_AREA_RATIO: 0.0
        BRIGHTNESS_JITTER_RATIO: 0.4
        CONTRAST_JITTER_RATIO: 0.4
        SATURATION_JITTER_RATIO: 0.4
```
