### ISSUE TITLE
如何在推理时resize到固定尺寸

### ISSUE THREAD

**Issue by bittergourd1224** [PaddlePaddle/PaddleSeg#3371]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在train和val时，都可以在配置文件中设置resize大小，例如：
```
train_dataset:
  transforms:
    - type: Resize
      target_size: [512, 512]
```
而在使用predict.py脚本推理时，如何进行自动resize？我试过如果在test_config下加上transforms是会报错的。请问该如何正确地修改配置文件？
