### ISSUE TITLE
图像分割效果随图片size变化周期性地产生偏移的问题

### ISSUE THREAD

**Issue by LHTcode** [PaddlePaddle/PaddleSeg#3385]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

用 paddleseg 提供的 MobileSeg 模型在眼球数据集(optic_disc_seg)上训练，使用 tools/predict.py 脚本对同一张图片的不同size进行推理，发现在图片的宽、高两个维度上分别对图片大小进行连续的变化，推理结果会产生**周期性的偏移**

**具体实验数据**
1. H维度图片 size 序列：(512, 511), (512,510), (512, 509), ...... , (512, 496), (512, 495)，共16张图片；
2. W维度图片 size 序列：(511, 512), (510, 512), (509, 512), ...... , (496, 512), (495, 512)，共16张图片。

**实验效果**
1. H维度图片(512,511), (512,509), (512,507), (512,505), (512,503), (512,501), (512,499), (512,497), (512,495)
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/77e6e377-aaa0-4652-abae-7c2c68b49c8e" height=100 />
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/eb457629-778f-4ae3-9d3d-1a94b8072e70" height=100/>
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/0d335670-8365-4890-a5f5-3bee0afda726" height=100/>
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/7791f883-5f9d-455b-9977-42b3ac90298a" height=100/>
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/f8302eb0-1929-45d8-a044-8bde20e37a9c" height=100/>
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/b61b8a1f-2806-4a42-9a95-46aa93c4088f" height=100/>
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/60adb251-07de-406b-90ea-d063bf8d9719" height=100/>
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/6eec4ab4-9a17-46f2-b6bc-af319ccd1df1" height=100/>
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/f0b921c6-e8fc-481a-9033-aa1984cebaec" height=100/>

3. W维度图片(511,512), (509,512), (507,512), (505,512), (503,512), (501,512), (499,512), (497,512), (495,512)
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/77e6e377-aaa0-4652-abae-7c2c68b49c8e" height=100 />
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/2c11487c-2595-4c1c-9568-d52dd738f1d5" height=100/>
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/09233e5f-7ad5-4b78-9d18-1587a751ce68" height=100/>
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/2ac8e83e-867f-49ac-ae13-37a7df0d2789" height=100/>
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/58300fbc-3c7c-4324-bd90-002d9adeec78" height=100/>
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/d842047a-2935-45c6-bfa6-39c59b368be5" height=100/>
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/5b322681-4d4c-4004-9fd3-251b4cf8b0ef" height=100/>
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/249f8c8e-4e9f-4b64-9b16-3a7a421122d9" height=100/>
<img src="https://github.com/PaddlePaddle/PaddleSeg/assets/75188358/48f06c39-49dc-4847-8fc4-459c2fd19d0a" height=100/>

如上图所示，变化周期大致为15(行/列像素)，在宽高两个维度上图像 size 分别递减到第16个像素时分割效果会发生突变，并且往往能够回复最佳的分割效果。同时，在多个 paddleseg 提供的模型中(PPLiteSeg、FCN、MobileSeg、UNet...)均有此现象，就不赘述了，在其他模型中此变化周期可能不同。并且我在自己的数据集上也复现了同样的现象。

同时，我使用 pytorch 单独训练的模型(UNet)并没有出现这种周期性的偏移现象

**下面是我的参数文件**
```yml
batch_size: 2
iters: 10000

train_dataset:
  type: Dataset
  dataset_root: data/optic_disc_seg
  train_path: data/optic_disc_seg/train_list.txt
  num_classes: 2
  mode: train
  transforms:
    - type: RandomPaddingCrop
      crop_size: [512, 512]
      im_padding_value: 0
      label_padding_value: 0
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: data/optic_disc_seg
  val_path: data/optic_disc_seg/val_list.txt
  num_classes: 2
  mode: val
  transforms:
    - type: Normalize

optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 1.0

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 130000
    - type: OhemCrossEntropyLoss
      min_kept: 130000
    - type: OhemCrossEntropyLoss
      min_kept: 130000
  coef: [1, 1, 1]

model:
  type: MobileSeg
  backbone:
    type: MobileNetV3_large_x1_0  # out channels: [24, 40, 112, 160]
    pretrained: https://paddleseg.bj.bcebos.com/dygraph/backbone/mobilenetv3_large_x1_0_ssld.tar.gz
  cm_bin_sizes: [1, 2, 4]
  cm_out_ch: 128
  arm_out_chs: [32, 64, 128]
  seg_head_inter_chs: [32, 32, 32]
```

无其余代码改动。

### 复现环境 Environment

- OS: Windows
- paddlepaddle-gpu: 2.4.2
- PaddleSeg: release/2.8.0
- Python: 3.9.13
- CUDA: 10.2
- CUDNN: 7605

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!
