### ISSUE TITLE
crop_size: [1024, 512]  ，Does 1024 mean the width or height of the image?

### ISSUE THREAD

**Issue by ZJDATY** [PaddlePaddle/PaddleSeg#3449]
```
  transforms: # 数据变换与数据增强
    - type: RandomPaddingCrop # 对图像和标注图进行随机裁剪
      crop_size: [1024, 512]
```
**下面我的图片是2560x1280的，想要训练出的模型是1X3X320X640的 。 crop_size: [640, 320]  ，设置成这样对吗？input_shape: [1, 3, 320, 640]设置成这样对吗？**

```
train:
  base_default:
    # 训练轮次的类型： 0: Epochs; 1: Iters
    epochs_iters_type: 0
    # 训练轮次
    epochs_iters: 3600
    batch_size: 32
    learning_rate: 0.01
    device: GPU
    gpu_num: 1 # 需要根据环境中的设备数配置
  # 记录配置
  base_current:
    epochs_iters_type: 0
    epochs_iters: 3600
    batch_size: 32
    learning_rate: 0.01
    device: GPU
    gpu_num: 1 # 需要根据环境中的设备数配置
  # 高级配置
  advance_default:
    # 自定义权重路径， 默认值为空
    resume_weight_path: 
    pretrain_weight_path: 
    # 可以填入：O1, O2, null（不开启）
    amp:
    # 动转静训练： true/false
    dy2st: false
    # 配置文件详情
    uapi_config_detail: '{}'
  # 记录配置
  advance_current:
    resume_weight_path: 
    pretrain_weight_path: output/iter_1200/model.pdparams
    amp:
    dy2st: false
    uapi_config_detail: '{}'
  # 模型输出目录，默认值
  output_dir: ./output
  output_dir_user: ./output
  crop_size: [640, 320]
evaluate:
  # 模型目录，将目录内所有.pdparams文件的全路径显示在"选择模型"中
  model_dir: ./output
  model_path: best_model/best.pdparams
  # 批量测试输出路径：
  output_dir: ./output/eval
  # 测试结果输出的json
  output_json: ./tmp/evaluate.json
  # 可以填入：O1, O2, None（否）
  device: GPU
  gpu_num: 1 # 需要根据环境中的设备数配置
  amp:
  input_shape: [1, 3, 320, 640]
```
