### ISSUE TITLE
请问config里面的model.pretrained和model.backbone.pretrained的区别是什么？

### ISSUE THREAD

**Issue by MooTong123** [PaddlePaddle/PaddleSeg#3476]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问config里面的model.pretrained和model.backbone.pretrained的区别是什么？我下载了一个预训练模型，是把这个文件地址放到model.pretrained还是model.backbone.pretrained呢？

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/44767255/8829090d-d98e-475c-994a-636428d887a2)

**Comment by Asthestarsfalll** [comment]
前者属于HRNet_W18，后者属于FCN

**Comment by MooTong123** [comment]
> 前者属于HRNet_W18，后者属于FCN

那比如说其他的模型PP-liteseg，文档里的下载的model是预训练模型？
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/44767255/bba80e5f-ab7d-4251-83ae-e8853b415ed7)


所以说这个下载的model.pdparams，是放到model.pretrained里？所以config是这样？

```
model:
  type: PPLiteSeg
  backbone:
    type: STDC1
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
  pretrained: ../pretrained/model.pdparams
```

还是说下载的这个model，直接放到model.backbone.pretrained里，这样也可以吗？
```
model:
  type: PPLiteSeg
  backbone:
    type: STDC1
    pretrained: ../pretrained/model.pdparams
```

**Comment by Asthestarsfalll** [comment]
@MooTong123 
performance下的一般都是训练好的权重，放在外层即可

**Comment by MooTong123** [comment]
> 

所以说是得下载两个模型？

```
model:
  type: PPLiteSeg
  backbone:
    type: STDC1
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz（需下载？）
  pretrained: ../pretrained/model.pdparams（需下载）
```
还是说直接下载一个performance里面，都放到这两个里面？因为只放到model.pretrained是跑不起来的，model.backbone.pretrained是必须要要有一个模型的。

所以下面这么放是可以的吗？
```
model:
  type: PPLiteSeg
  backbone:
    type: STDC1
    pretrained:  ../pretrained/model.pdparams
  pretrained: ../pretrained/model.pdparams
```

**Comment by MooTong123** [comment]
> 

还是说performance的model直接放到model.backbone.pretrained里？model.pretrained就不加了？所以哪种形式是正确的？

```
model:
  type: PPLiteSeg
  backbone:
    type: STDC1
    pretrained:  ../pretrained/model.pdparams
```
