### ISSUE TITLE
How to lock layers for fine-tuning 

### ISSUE THREAD

**Issue by danielvandenberg95** [PaddlePaddle/PaddleSeg#3490]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

While using tools/train.py, how do I lock all but the last layer for fine-tuning?

Ideally using only config or commands, I can't change any python files.

**Comment by Asthestarsfalll** [comment]
You can refer to [here](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/configs/segnext/segnext_mscan_b_cityscapes_1024x1024_160k.yml#L31-L35)  and set `lr_mult` to `0.0`.

**Comment by danielvandenberg95** [comment]
How do I know what names do what?
Is "head" all but the last layer?
Would this not simply lock all layers?

I'm using HarDNet

**Comment by Asthestarsfalll** [comment]
> How do I know what names do what? Is "head" all but the last layer? Would this not simply lock all layers?
> 
> I'm using HarDNet

It will match the names of all the layers. Those layers with names which contain the taget name will be set.

For HarDNet, you should use
```yaml

  custom_cfg:
    - name: stem
      lr_mult: 0.0
    - name: encoder
      lr_mult: 0.0
    - name: decoder
      lr_mult: 0.0
```

**Comment by danielvandenberg95** [comment]
Ah, and then it only leaves cls_head untouched, so that one is trained. Awesome, thanks! Should this perhaps be documented better?

**Comment by Asthestarsfalll** [comment]
Yes, we will improve the documentation resently.

**Comment by danielvandenberg95** [comment]
Okay, unfortunately I'm reopening this issue. Without custom_cfg my training works fine. But now I'm getting an error.

Config:
```
batch_size: 4
iters: 160
loss:
  coef:
  - 1
  types:
  - loss_th: 0.3
    min_K: 4096
    type: BootstrappedCrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.002
  power: 1
  type: PolynomialDecay
  warmup_iters: 5
  warmup_start_lr: 1.0e-10
model:
  num_classes: 2
  type: HarDNet
optimizer:
  beta1: 0.9
  beta2: 0.999
  custom_cfg:
  - lr_mult: 0.0
    name: stem
  - lr_mult: 0.0
    name: encoder
  - lr_mult: 0.0
    name: decoder
  type: AdamW
  weight_decay: 0.01
test_config:
  scales:
  - 0.05
test_dataset:
  dataset_root: /my_dataset/
  mode: test
  num_classes: 2
  separator: _---_
  test_path: /my_dataset/test.txt
  transforms:
  - type: Normalize
  type: Dataset
train_dataset:
  dataset_root: /my_dataset/
  mode: train
  num_classes: 2
  separator: _---_
  train_path: /my_dataset/train.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 1024
    - 512
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: /my_dataset/
  mode: val
  num_classes: 2
  separator: _---_
  transforms:
  - type: Normalize
  type: Dataset
  val_path: /my_dataset/val.txt
```

Error:
```
2023-09-18 11:53:35 [INFO]      Use the following config to build optimizer                                                                              
optimizer:                                                                  
  beta1: 0.9                                                                
  beta2: 0.999                                                              
  custom_cfg:                                                               
  - lr_mult: 0.0                                                            
    name: stem                                                              
  - lr_mult: 0.0                                                                                                                                                                                                                                                                                                   
    name: encoder                                                           
  - lr_mult: 0.0                                                                                                                                                                                                                                                                                                   
    name: decoder                                                                                                                                                                                                                                                                                                  
  type: AdamW                                                                                                                                                                                                                                                                                                      
  weight_decay: 0.01                                                                                                                                                                                                                                                                                               
2023-09-18 11:53:35 [INFO]      Parameter groups for optimizer:                                                                                                                                                                                                                                                    
Group 0:                                                                                                                                                                                                                                                                                                           
{'lr_mult': 0.0, 'name': 'stem', 'params_name': ['conv2d_0.w_0', 'batch_norm2d_0.w_0', 'batch_norm2d_0.b_0', 'conv2d_1.w_0', 'batch_norm2d_1.w_0', 'batch_norm2d_1.b_0', 'conv2d_2.w_0', 'batch_norm2d_2.w_0', 'batch_norm2d_2.b_0', 'conv2d_3.w_0', 'batch_norm2d_3.w_0', 'batch_norm2d_3.b_0']}                  
Group 1:                                                                                                                                                                                                                                                                                                           
{'lr_mult': 0.0, 'name': 'encoder', 'params_name': ['conv2d_4.w_0', 'batch_norm2d_4.w_0', 'batch_norm2d_4.b_0', 'conv2d_5.w_0', 'batch_norm2d_5.w_0', 'batch_norm2d_5.b_0', 'conv2d_6.w_0', 'batch_norm2d_6.w_0', 'batch_norm2d_6.b_0', 'conv2d_7.w_0', 'batch_norm2d_7.w_0', 'batch_norm2d_7.b_0', 'conv2d_8.w_0',
 'batch_norm2d_8.w_0', 'batch_norm2d_8.b_0', 'conv2d_9.w_0', 'batch_norm2d_9.w_0', 'batch_norm2d_9.b_0', 'conv2d_10.w_0', 'batch_norm2d_10.w_0', 'batch_norm2d_10.b_0', 'conv2d_11.w_0', 'batch_norm2d_11.w_0', 'batch_norm2d_11.b_0', 'conv2d_12.w_0', 'batch_norm2d_12.w_0', 'batch_norm2d_12.b_0', 'conv2d_13.w_
0', 'batch_norm2d_13.w_0', 'batch_norm2d_13.b_0', 'conv2d_14.w_0', 'batch_norm2d_14.w_0', 'batch_norm2d_14.b_0', 'conv2d_15.w_0', 'batch_norm2d_15.w_0', 'batch_norm2d_15.b_0', 'conv2d_16.w_0', 'batch_norm2d_16.w_0', 'batch_norm2d_16.b_0', 'conv2d_17.w_0', 'batch_norm2d_17.w_0', 'batch_norm2d_17.b_0', 'conv
2d_18.w_0', 'batch_norm2d_18.w_0', 'batch_norm2d_18.b_0', 'conv2d_19.w_0', 'batch_norm2d_19.w_0', 'batch_norm2d_19.b_0', 'conv2d_20.w_0', 'batch_norm2d_20.w_0', 'batch_norm2d_20.b_0', 'conv2d_21.w_0', 'batch_norm2d_21.w_0', 'batch_norm2d_21.b_0', 'conv2d_22.w_0', 'batch_norm2d_22.w_0', 'batch_norm2d_22.b_0
', 'conv2d_23.w_0', 'batch_norm2d_23.w_0', 'batch_norm2d_23.b_0', 'conv2d_24.w_0', 'batch_norm2d_24.w_0', 'batch_norm2d_24.b_0', 'conv2d_25.w_0', 'batch_norm2d_25.w_0', 'batch_norm2d_25.b_0', 'conv2d_26.w_0', 'batch_norm2d_26.w_0', 'batch_norm2d_26.b_0', 'conv2d_27.w_0', 'batch_norm2d_27.w_0', 'batch_norm2
d_27.b_0', 'conv2d_28.w_0', 'batch_norm2d_28.w_0', 'batch_norm2d_28.b_0', 'conv2d_29.w_0', 'batch_norm2d_29.w_0', 'batch_norm2d_29.b_0', 'conv2d_30.w_0', 'batch_norm2d_30.w_0', 'batch_norm2d_30.b_0', 'conv2d_31.w_0', 'batch_norm2d_31.w_0', 'batch_norm2d_31.b_0', 'conv2d_32.w_0', 'batch_norm2d_32.w_0', 'bat
ch_norm2d_32.b_0', 'conv2d_33.w_0', 'batch_norm2d_33.w_0', 'batch_norm2d_33.b_0', 'conv2d_34.w_0', 'batch_norm2d_34.w_0', 'batch_norm2d_34.b_0', 'conv2d_35.w_0', 'batch_norm2d_35.w_0', 'batch_norm2d_35.b_0', 'conv2d_36.w_0', 'batch_norm2d_36.w_0', 'batch_norm2d_36.b_0', 'conv2d_37.w_0', 'batch_norm2d_37.w_
0', 'batch_norm2d_37.b_0', 'conv2d_38.w_0', 'batch_norm2d_38.w_0', 'batch_norm2d_38.b_0', 'conv2d_39.w_0', 'batch_norm2d_39.w_0', 'batch_norm2d_39.b_0', 'conv2d_40.w_0', 'batch_norm2d_40.w_0', 'batch_norm2d_40.b_0']} 
Group 2:                                                                    
{'lr_mult': 0.0, 'name': 'decoder', 'params_name': ['conv2d_42.w_0', 'batch_norm2d_42.w_0', 'batch_norm2d_42.b_0', 'conv2d_43.w_0', 'batch_norm2d_43.w_0', 'batch_norm2d_43.b_0', 'conv2d_44.w_0', 'batch_norm2d_44.w_0', 'batch_norm2d_44.b_0', 'conv2d_45.w_0', 'batch_norm2d_45.w_0', 'batch_norm2d_45.b_0', 'co
nv2d_46.w_0', 'batch_norm2d_46.w_0', 'batch_norm2d_46.b_0', 'conv2d_47.w_0', 'batch_norm2d_47.w_0', 'batch_norm2d_47.b_0', 'conv2d_48.w_0', 'batch_norm2d_48.w_0', 'batch_norm2d_48.b_0', 'conv2d_49.w_0', 'batch_norm2d_49.w_0', 'batch_norm2d_49.b_0', 'conv2d_51.w_0', 'batch_norm2d_51.w_0', 'batch_norm2d_51.b
_0', 'conv2d_52.w_0', 'batch_norm2d_52.w_0', 'batch_norm2d_52.b_0', 'conv2d_53.w_0', 'batch_norm2d_53.w_0', 'batch_norm2d_53.b_0', 'conv2d_54.w_0', 'batch_norm2d_54.w_0', 'batch_norm2d_54.b_0', 'conv2d_55.w_0', 'batch_norm2d_55.w_0', 'batch_norm2d_55.b_0', 'conv2d_56.w_0', 'batch_norm2d_56.w_0', 'batch_nor
m2d_56.b_0', 'conv2d_57.w_0', 'batch_norm2d_57.w_0', 'batch_norm2d_57.b_0', 'conv2d_58.w_0', 'batch_norm2d_58.w_0', 'batch_norm2d_58.b_0', 'conv2d_60.w_0', 'batch_norm2d_60.w_0', 'batch_norm2d_60.b_0', 'conv2d_61.w_0', 'batch_norm2d_61.w_0', 'batch_norm2d_61.b_0', 'conv2d_62.w_0', 'batch_norm2d_62.w_0', 'b
atch_norm2d_62.b_0', 'conv2d_63.w_0', 'batch_norm2d_63.w_0', 'batch_norm2d_63.b_0', 'conv2d_65.w_0', 'batch_norm2d_65.w_0', 'batch_norm2d_65.b_0', 'conv2d_66.w_0', 'batch_norm2d_66.w_0', 'batch_norm2d_66.b_0', 'conv2d_67.w_0', 'batch_norm2d_67.w_0', 'batch_norm2d_67.b_0', 'conv2d_68.w_0', 'batch_norm2d_68.
w_0', 'batch_norm2d_68.b_0', 'conv2d_41.w_0', 'batch_norm2d_41.w_0', 'batch_norm2d_41.b_0', 'conv2d_50.w_0', 'batch_norm2d_50.w_0', 'batch_norm2d_50.b_0', 'conv2d_59.w_0', 'batch_norm2d_59.w_0', 'batch_norm2d_59.b_0', 'conv2d_64.w_0', 'batch_norm2d_64.w_0', 'batch_norm2d_64.b_0']} 
Last group:                                                                 
 params_name: ['conv2d_69.w_0', 'conv2d_69.b_0']                            
2023-09-18 11:53:35 [INFO]      Use the following config to build loss      
loss:                                                                                                                                                    
  coef:                                                                     
  - 1                                                                                                                                                    
  types:                                                                    
  - loss_th: 0.3                                                            
    min_K: 4096                                                             
    type: BootstrappedCrossEntropyLoss                                      
2023-09-18 11:53:37 [INFO]      use AMP to train. AMP level = O2            
/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/norm.py:777: UserWarning: When training, we now always track global mean and variance.
  warnings.warn(
Traceback (most recent call last):
  File "tools/train.py", line 195, in <module>
    main(args)
  File "tools/train.py", line 170, in main
    train(
  File "/data/repos/PaddleSeg/paddleseg/core/train.py", line 225, in train
    scaler.minimize(optimizer, scaled)  # update parameters
  File "/usr/local/lib/python3.8/dist-packages/paddle/amp/grad_scaler.py", line 715, in minimize
    return super().minimize(optimizer, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/amp/grad_scaler.py", line 249, in minimize
    optimize_ops, params_grads = optimizer.minimize(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/base.py", line 347, in _decorate_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/optimizer/optimizer.py", line 1476, in minimize
    params_grads = self.backward(
  File "/usr/local/lib/python3.8/dist-packages/paddle/optimizer/optimizer.py", line 1132, in backward
    grads = core.eager.get_all_grads(parameter_list)
ValueError: (InvalidArgument) argument (position 1) must be list of Tensor, but got dict at pos 0 (at /root/Paddle/paddle/fluid/pybind/eager_utils.cc:263)
```

How do I fix this?
