### ISSUE TITLE
backbone_lr_mult can not be used. 无法使用该参数

### ISSUE THREAD

**Issue by manfrey666** [PaddlePaddle/PaddleSeg#3493]
### Bug描述 Describe the Bug

按照官方提供的[训练技巧](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/docs/train/train_tricks_cn.md)：在`optimizer`配置字段中设置`backbone_lr_mult`，可以设置模型Backbone和Head使用不同学习率。
于是我在[quick_start](https://github.com/PaddlePaddle/PaddleSeg/blob/aa41c725fcb3fa88e7f02bf71eaa7240b68b3bac/docs/quick_start_cn.md)的基础上，在配置文件的`optimizer`字段中添加了`backbone_lr_mult`。
但是发现训练报错，报错信息如下：

```
File "/home/udf/workspace/yzh/Projects/PaddleSeg/paddleseg/cvlibs/builder.py", line 72, in build_component
    raise RuntimeError(
RuntimeError: Tried to create a Momentum object, but the operation has failed. Please double check the arguments used to create the object.
The error message is: 
__init__() got an unexpected keyword argument 'backbone_lr_mult'
```

配置文件如下：
```
batch_size: 4
iters: 3000

train_dataset:
  type: Dataset
  dataset_root: data/optic_disc_seg
  train_path: data/optic_disc_seg/train_list.txt
  num_classes: 2
  mode: train
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: data/optic_disc_seg
  val_path: data/optic_disc_seg/val_list.txt
  num_classes: 2
  mode: val
  transforms:
    - type: Normalize

optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 4.0e-5
  backbone_lr_mult: 0.1

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 1, 1]


model:
  type: PPLiteSeg
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz
```

请问是还不支持这个参数吗？

### 复现环境 Environment

- OS: Ubuntu 20.04.5 LTS
- PaddlePaddle: 2.4.2 or 2.5.0
- Python: 3.8.17
- CUDA: 11.6
- CUDNN: 8.5.0
- GCC: 9.4.0

**Comment by Asthestarsfalll** [comment]
这个参数后面移除了，可以在配置文件中使用:
```yml
optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 4.0e-5
  custom_cfg:
   - name: backbone
     lr_mult: 0.1

```
