### ISSUE TITLE
Usage of EmptyDir volume "dshm" exceeds the limit "512Mi". 

### ISSUE THREAD

**Issue by LisaShen0509** [PaddlePaddle/PaddleSeg#3640]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在openpai集群使用自制数据集（图片大小512x512）训练ppmattingv2时遇到了问题
部分配置如下:
```
batch_size: 8
iters: 100
```
运行代码：
```
export CUDA_VISIBLE_DEVICES=0
python tools/train.py \
       --config configs/ppmattingv2/ppmattingv2-stdc1-human_512.yml \
       --do_eval \
       --use_vdl \
       --save_interval 15 \
       --num_workers 5 \
       --save_dir output/ppmattingv2_wifi
```
可以成功初始化模型，但是控制台输出如下信息后就出错了:
```
/mnt/share/syl/vf_env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:778: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance."
size : [128, 128]
size : [256, 256]
size : [64, 64]
```
错误信息：
```
[Exit Trigger Info]

ExitTriggerMessage: FailedTaskCount 1 has reached MinFailedTaskCount 1 in the TaskRole
ExitTriggerTaskRole: taskrole
ExitTriggerTaskIndex: 0

--------------------------------------------------------------------------------

[Exit Spec]

code: -1000
phrase: PodEvicted
issuer: PAI_K8S
causer: PAI_K8S
type: PLATFORM_FAILURE
stage: RUNNING
behavior: TRANSIENT
reaction: ALWAYS_RETRY
reason: 'Pod is evicted by K8S, maybe its node is out of resource'
repro:
  - Start a raw process on the host to use up almost all memory on the node
solution:
  - Wait result from next retry
  - Contact Cluster Admin
pattern:
  controllerPodPatterns:
    - reasonRegex: (?i)^Evicted$
      messageRegex: (?ms).*


--------------------------------------------------------------------------------

[Exit Diagnostics]

Pod failed: PodPattern matched:
reason: Evicted
message: 'Usage of EmptyDir volume "dshm" exceeds the limit "512Mi". '
```
使用PPM-100数据集训练也报同样的错误，但是跑其他代码不会出现这个错误

请问有人遇到过这个错误吗？
