### ISSUE TITLE
hrnet训练时间过长

### ISSUE THREAD

**Issue by wwma** [PaddlePaddle/PaddleSeg#3847]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用hrnet进行模型训练，在训练初始阶段，训练时间很正常，但是当进行第一次模型评估之后，训练时间骤增，且显存占用情况也增加，请问是有什么问题吗？
![image](https://github.com/user-attachments/assets/b5e1e039-f472-42f8-9ad4-c57d532d0a29)
以下是配置文件：

```
# _base_: '../_base_/cityscapes.yml'

batch_size: 2
iters: 60000

train_dataset:
  type: Dataset
  dataset_root: dataset\bridge_new
  train_path: dataset\bridge_new\train.txt
  num_classes: 5
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: dataset\bridge_new
  val_path: dataset\bridge_new\val.txt
  num_classes: 5
  transforms:
    - type: Normalize
  mode: val

optimizer:
  type: SGD
  weight_decay: 0.0002

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.005
  end_lr: 0
  power: 0.9


loss:
  types:
    - type: CrossEntropyLoss
    - type: PixelContrastCrossEntropyLoss
      temperature: 0.1
      base_temperature: 0.07
      ignore_index: 255
      max_samples: 1024
      max_views: 100
  coef: [1, 0.1]

model:
  type: HRNetW48Contrast
  backbone:
    type: HRNet_W48
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
  bb_channels: 720
  drop_prob: 0.1
  proj_dim: 720
```
