### ISSUE TITLE
关于训练和评估时候的图像尺寸问题

### ISSUE THREAD

**Issue by David-dotcom666** [PaddlePaddle/PaddleSeg#3867]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

1.我在train_dataset的transforms使用了    
- type: Resize
      target_size: [ 512, 512 ]
那么我在val_dataset也需要
- type: Resize
      target_size: [ 512, 512 ]
这样才能保持训练和评估尺寸的一致性吗？
2.如果我在rain_dataset的transforms使用了    
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 0.5
      scale_step_size: 0
那么这个时候我在val_dataset中的transforms要怎么设置呢？我试了也设置成这样，在评估的时候会报标注和pred尺寸不一致。如果在val_dataset不设置尺寸倒是可以，但是这时候评估的是原图尺寸上的评估吧？我想在评估也进行自动一半尺寸的。这时候网络的输入尺寸是多少呢？是原图吗？导出模型尺寸设置多少合适？

我目前的需求是可以训练不同尺寸的图，且可以选择训练精度。例如0.5，我就使用ResizeStepScaling到固定的0.5，然后我在导出后的模型预处理的时候先把图像进行ResizeStepScaling，然后padding到导出的尺寸。

**Comment by Bobholamovic** [comment]
你好，训练和评估的尺寸并不一定要一模一样；通常在训练时可以进行随机resize，但评估阶段需要resize到一个固定的尺寸。如果不进行设置，通常评估时将使用原图尺寸。具体的训练、验证输入尺寸选择取决于您使用的模型和数据集，并没有一个标准答案。通常，分割模型在模型输入尺寸上具备一定的泛化性能。

**Comment by David-dotcom666** [comment]
> 你好，训练和评估的尺寸并不一定要一模一样；通常在训练时可以进行随机resize，但评估阶段需要resize到一个固定的尺寸。如果不进行设置，通常评估时将使用原图尺寸。具体的训练、验证输入尺寸选择取决于您使用的模型和数据集，并没有一个标准答案。通常，分割模型在模型输入尺寸上具备一定的泛化性能。
谢谢回答，我想请教一个问题，我看市面上有一些商业软件做到了样本数量很少，甚至只有1.2张的情况下训练出的效果也还不错。我想请教下，对于这种情况，基本上样本都是不平衡的而且差的非常多，什么样的loss组合会比较泛用呢？我看了一些帖提到CE或者multiclass的，那么这些我在使用的时候需要加权重吗？最近在测试pplite-seg，它默认使用三个loss，三个loss是平等的吗

**Comment by Bobholamovic** [comment]
在样本类别非常不平衡的情况下，一种常见且有效的做法是在损失函数中考虑这一点，例如为多类的CE loss添加类别权重。以PP-LiteSeg为例，配置文件[`pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.yml`](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.10/configs/pp_liteseg/pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.yml) 中对损失函数的配置如下：

```yaml
loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 130000   # batch_size * 1024 * 512 // 16
    - type: OhemCrossEntropyLoss
      min_kept: 130000
    - type: OhemCrossEntropyLoss
      min_kept: 130000
  coef: [1, 1, 1]
```

该模型在训练阶段给出3个输出（1个主要输出和2个辅助输出），以上配置对每个输出都使用`OhemCrossEntropyLoss`和标签计算损失，得到的三个loss以`coef`指定的系数`[1, 1, 1]`加权求和。要想对其中的每个损失函数增加类别权重，可以将配置修改如下：

```yaml
loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 130000   # batch_size * 1024 * 512 // 16
      weight: [0.5, 0.2, 0.3]
    - type: OhemCrossEntropyLoss
      min_kept: 130000
      weight: [0.5, 0.2, 0.3]
    - type: OhemCrossEntropyLoss
      min_kept: 130000
      weight: [0.5, 0.2, 0.3]
  coef: [1, 1, 1]
```

以上的设置将（对于每个损失函数）为第0类添加0.5的权重，为第1类和第2类分别添加0.2和0.3的权重。
