### ISSUE TITLE
Lovasz loss 震荡

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleSeg#435]
我尝试使用 Lovasz loss 解决分类不平衡的问题，但是，好像它不是收敛的， loss 一直在震荡；
我是这样设置的：
```
SOLVER:
    LR: 0.005
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    LOSS: ["lovasz_softmax_loss","softmax_loss"]
    LOSS_WEIGHT:
        LOVASZ_SOFTMAX_LOSS: 0.2
        SOFTMAX_LOSS: 0.8
```
我能通过什么办法让它收敛？
