### ISSUE TITLE
使用Lovasz loss 训练时出错

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleSeg#523]
训练一段时间之后突然循环报错以下信息（数据集已经通过脚本校验没有问题）：
```
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::GpuMemcpyAsync(void*, void const*, unsigned long, cudaMemcpyKind, CUstream_st*)
3   void paddle::memory::Copy<paddle::platform::CUDAPlace, paddle::platform::CPUPlace>(paddle::platform::CUDAPlace, void*, paddle::platform::CPUPlace, void const*, unsigned long, CUstream_st*)
4   paddle::framework::details::OpHandleBase::RunAndRecordEvent(std::function<void ()> const&)
5   paddle::framework::details::ScaleLossGradOpHandle::RunImpl()
6   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
7   paddle::framework::details::FastThreadedSSAGraphExecutor::RunTracedOps(std::vector<paddle::framework::details::OpHandleBase*, std::allocator<paddle::framework::details::OpHandleBase*> > const&)
8   paddle::framework::details::FastThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, bool)
9   paddle::framework::details::ScopeBufferedMonitor::Apply(std::function<void ()> const&, bool)
10  paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, bool)
11  paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, bool)

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(77), an illegal memory access was encountered.
  [Advise: The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] at (/paddle/paddle/fluid/platform/gpu_info.cc:276)
```
配置文件如下：
```
EVAL_CROP_SIZE: (1920, 720) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (512, 512) # (width, height), for unpadding rangescaling and stepscaling
AUG:
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (1024, 1024) # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
    RICH_CROP:
        ENABLE: True
        BLUR: True
        BLUR_RATIO: 0.2
        MAX_ROTATION: 90
        BRIGHTNESS_JITTER_RATIO: 0.5
        SATURATION_JITTER_RATIO: 0.5
        CONTRAST_JITTER_RATIO: 0.5
BATCH_SIZE: 2
DATASET:
    DATA_DIR: "./dataset/8156_cut/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 2
    TEST_FILE_LIST: "dataset/8156_cut/val.txt"
    TRAIN_FILE_LIST: "dataset/8156_cut/train.txt"
    VAL_FILE_LIST: "dataset/8156_cut/val.txt"
    IGNORE_INDEX: 255
    SEPARATOR: " "
DATALOADER:
    # 数据载入时的并发数, 建议值8
    NUM_WORKERS: 8
    # 数据载入时缓存队列大小, 建议值256
    BUF_SIZE: 256

FREEZE:
    MODEL_FILENAME: "model"
    PARAMS_FILENAME: "params"
MODEL:
    DEFAULT_NORM_TYPE: "bn"
    MODEL_NAME: "deeplabv3p"
    DEEPLAB:
        ASPP_WITH_SEP_CONV: True
        DECODER_USE_SEP_CONV: True
        OUTPUT_STRIDE: 8
TRAIN:
    PRETRAINED_MODEL_DIR: u"pretrained_model/deeplabv3p_xception65_bn_cityscapes"
    MODEL_SAVE_DIR: "saved_model/8156_cut"
    RESUME_MODEL_DIR: ""
    SNAPSHOT_EPOCH: 20
TEST:
    TEST_MODEL: "saved_model/competition/final"
SOLVER:
    LR: 0.01
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 100
    LOSS: ["lovasz_hinge_loss","bce_loss"]
    LOSS_WEIGHT:
        LOVASZ_HINGE_LOSS: 0.5
        BCE_LOSS: 0.5
```
