### ISSUE TITLE
为什么vis.py的可视化结果跟最后部署后的infer.py评估的模型结果不一样

### ISSUE THREAD

**Issue by lantudou** [PaddlePaddle/PaddleSeg#670]
模型训练好之后使用export model导出并使用infer.py对训练集的数据进行评估，出来的伪彩色结果标注图跟训练过程中的vis.py效果相比低了很多，环境用的是AI studio的线上环境

```
EVAL_CROP_SIZE: (800, 800) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (800, 800) # (width, height), for unpadding rangescaling and stepscaling
AUG:
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (800, 800)
    MIN_SCALE_FACTOR: 0.5
    MAX_SCALE_FACTOR: 2
    MIRROR: True
    FLIP: True
    RICH_CROP.BLUR: True
    RICH_CROP.MAX_ROTATION: 90
    RICH_CROP.BRIGHTNESS_JITTER_RATIO: 0.7
    RICH_CROP.CONTRAST_JITTER_RATIO: 0.4
    TO_RGB: True 
BATCH_SIZE: 6  #批处理大小
DATASET:
    DATA_DIR: "/home/aistudio/work/dataset/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 4
    TEST_FILE_LIST: "/home/aistudio/work/dataset/val_list.txt"
    TRAIN_FILE_LIST: "/home/aistudio/work/dataset/train_list.txt"
    VAL_FILE_LIST: "/home/aistudio/work/dataset/val_list.txt"
    VIS_FILE_LIST: "/home/aistudio/work/dataset/train_list.txt"
    IGNORE_INDEX: 255
    SEPARATOR: " "
FREEZE:
    MODEL_FILENAME: "model"
    PARAMS_FILENAME: "params"
MODEL:
    DEFAULT_NORM_TYPE: "bn"
    MODEL_NAME: "deeplabv3p"
    DEEPLAB:
        BACKBONE: "mobilenetv3_large"
        ASPP_WITH_SEP_CONV: True
        DECODER_USE_SEP_CONV: True
        ENCODER_WITH_ASPP: True
        ENABLE_DECODER: True
        OUTPUT_STRIDE: 32
        BACKBONE_LR_MULT_LIST: [0.15,0.35,0.65,0.85,1]
        ENCODER:
            POOLING_STRIDE: (4, 5)
            POOLING_CROP_SIZE: (769, 769)
            ASPP_WITH_SE: True
            SE_USE_QSIGMOID: True
            ASPP_CONVS_FILTERS: 128
            ASPP_WITH_CONCAT_PROJECTION: False
            ADD_IMAGE_LEVEL_FEATURE: False
        DECODER:
            USE_SUM_MERGE: True
            CONV_FILTERS: 4
            OUTPUT_IS_LOGITS: True

TRAIN:
    PRETRAINED_MODEL_DIR: "./pretrained_model/deeplab_mobilenetv3/"
    MODEL_SAVE_DIR: "./saved_model/deeplab_mobilenetv3/"
    SNAPSHOT_EPOCH: 50
TEST:
    TEST_MODEL: "./saved_model/deeplab_mobilenetv3/final"
SOLVER:
    NUM_EPOCHS: 600  #训练epoch数，正整数
    LR: 0.001  #初始学习率
    OPTIMIZER: "adam" #优化算法, 选项为sgd和adam
    LOSS: ["lovasz_softmax_loss","softmax_loss"]
    LOSS_WEIGHT:
        LOVASZ_SOFTMAX_LOSS: 0.4
        SOFTMAX_LOSS: 0.6
    CROSS_ENTROPY_WEIGHT: "dynamic"
```

```
!python /home/aistudio/PaddleSeg/pdseg/eval.py   --cfg /home/aistudio/work/dataset/config2.yaml \TEST.TEST_MODEL saved_model/deeplab_mobilenetv3/best_model

[EVAL]step=1 loss=0.07061 acc=0.9921 IoU=0.8767 step/sec=0.14 | ETA 00:00:00
[EVAL]#image=4 acc=0.9921 IoU=0.8767
[EVAL]Category IoU: [0.9914 0.9400 0.9446 0.6308]
[EVAL]Category Acc: [0.9969 0.9588 0.9512 0.8240]
[EVAL]Kappa:0.9530


```

```
!python /home/aistudio/PaddleSeg/pdseg/export_model.py --cfg /home/aistudio/work/dataset/config2.yaml \TEST.TEST_MODEL saved_model/deeplab_mobilenetv3/best_model

!pip install -r PaddleSeg/deploy/python/requirements.txt
!python PaddleSeg/deploy/python/infer.py --conf=freeze_model/deploy.yaml --input_dir=test
```

![33_jpeg_result](https://user-images.githubusercontent.com/34973475/101857643-ef45c580-3ba2-11eb-8576-5f858f93e5ab.png)
![33](https://user-images.githubusercontent.com/34973475/101857645-f10f8900-3ba2-11eb-8ce6-fc868fddc34d.png)

结果相差确实挺多的，如有必要我可以把项目设置成公开项目提供复现协助
